{
  "hash": "228c619e884670226993a6157178c47f",
  "result": {
    "markdown": "---\ntitle: \"Laptop Price Prediction\"\nauthor: \"Ajay Shankar A\"\ndate: \"2025-06-18\"\nformat: \n  html:\n    page-layout: full\n  docx: default\ncategories: [Code, EDA, ML]\n---\n\n# Laptop Price Prediction\n\nThis project aims to predict laptop prices based on various features such as specifications, brand, and market.\n\n## Data Description\n\nThe dataset used for this project is sourced from Kaggle. It contains detailed information about various laptop models, including specifications such as processor type, RAM, storage, display size, and brand. The target variable is the price of the laptops.\n\n## Client's Objectives:\n\n### Accurate Pricing:\n\nDevelop a model that can accurately predict laptop prices based on various features, helping our clients stay competitive in the market.\n\n### Market Positioning:\n\nUnderstand how different features contribute to pricing, enabling SmartTech Co. to strategically position its laptops in the market.\n\n### Brand Influence:\n\nAssess the impact of brand reputation on pricing, providing insights into brand perception and market demand.\n\n## Loading Libraries and Dataset\n\n### Importing Libraries\n\nPandas, NumPy, Matplotlib, and Seaborn are used for data manipulation, numerical operations, and visualization.\n\n::: {.cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n```\n:::\n\n\nImporting dataset\n\n::: {.cell execution_count=2}\n``` {.python .cell-code}\ndf = pd.read_csv(\"F:/Odin_school/Capstone_projects/ml_capstone/laptop.csv\")\n\ndf.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=62}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Unnamed: 0.1</th>\n      <th>Unnamed: 0</th>\n      <th>Company</th>\n      <th>TypeName</th>\n      <th>Inches</th>\n      <th>ScreenResolution</th>\n      <th>Cpu</th>\n      <th>Ram</th>\n      <th>Memory</th>\n      <th>Gpu</th>\n      <th>OpSys</th>\n      <th>Weight</th>\n      <th>Price</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0</td>\n      <td>0.0</td>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>13.3</td>\n      <td>IPS Panel Retina Display 2560x1600</td>\n      <td>Intel Core i5 2.3GHz</td>\n      <td>8GB</td>\n      <td>128GB SSD</td>\n      <td>Intel Iris Plus Graphics 640</td>\n      <td>macOS</td>\n      <td>1.37kg</td>\n      <td>71378.6832</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1</td>\n      <td>1.0</td>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>13.3</td>\n      <td>1440x900</td>\n      <td>Intel Core i5 1.8GHz</td>\n      <td>8GB</td>\n      <td>128GB Flash Storage</td>\n      <td>Intel HD Graphics 6000</td>\n      <td>macOS</td>\n      <td>1.34kg</td>\n      <td>47895.5232</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2</td>\n      <td>2.0</td>\n      <td>HP</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>Full HD 1920x1080</td>\n      <td>Intel Core i5 7200U 2.5GHz</td>\n      <td>8GB</td>\n      <td>256GB SSD</td>\n      <td>Intel HD Graphics 620</td>\n      <td>No OS</td>\n      <td>1.86kg</td>\n      <td>30636.0000</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>3</td>\n      <td>3.0</td>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>15.4</td>\n      <td>IPS Panel Retina Display 2880x1800</td>\n      <td>Intel Core i7 2.7GHz</td>\n      <td>16GB</td>\n      <td>512GB SSD</td>\n      <td>AMD Radeon Pro 455</td>\n      <td>macOS</td>\n      <td>1.83kg</td>\n      <td>135195.3360</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>4</td>\n      <td>4.0</td>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>13.3</td>\n      <td>IPS Panel Retina Display 2560x1600</td>\n      <td>Intel Core i5 3.1GHz</td>\n      <td>8GB</td>\n      <td>256GB SSD</td>\n      <td>Intel Iris Plus Graphics 650</td>\n      <td>macOS</td>\n      <td>1.37kg</td>\n      <td>96095.8080</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Data Cleansing\n\n### Checking for Missing Values\n\n::: {.cell execution_count=3}\n``` {.python .cell-code}\ndf.isnull().sum()\n```\n\n::: {.cell-output .cell-output-display execution_count=63}\n```\nUnnamed: 0.1         0\nUnnamed: 0          30\nCompany             30\nTypeName            30\nInches              30\nScreenResolution    30\nCpu                 30\nRam                 30\nMemory              30\nGpu                 30\nOpSys               30\nWeight              30\nPrice               30\ndtype: int64\n```\n:::\n:::\n\n\nAll columns except `Unnamed: 0.1` has missing values, which might mean that first column may just be an index column. Let's drop it and check `Unnamed: 0` column.\n\n::: {.cell execution_count=4}\n``` {.python .cell-code}\ndf = df.drop(['Unnamed: 0.1'], axis=1)\n\ndf.isnull().sum()\n```\n\n::: {.cell-output .cell-output-display execution_count=64}\n```\nUnnamed: 0          30\nCompany             30\nTypeName            30\nInches              30\nScreenResolution    30\nCpu                 30\nRam                 30\nMemory              30\nGpu                 30\nOpSys               30\nWeight              30\nPrice               30\ndtype: int64\n```\n:::\n:::\n\n\n`Null` values are still present lets drop the rows with `Null` values.\n\n::: {.cell execution_count=5}\n``` {.python .cell-code}\ndf = df.dropna()\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nIndex: 1273 entries, 0 to 1302\nData columns (total 12 columns):\n #   Column            Non-Null Count  Dtype  \n---  ------            --------------  -----  \n 0   Unnamed: 0        1273 non-null   float64\n 1   Company           1273 non-null   object \n 2   TypeName          1273 non-null   object \n 3   Inches            1273 non-null   object \n 4   ScreenResolution  1273 non-null   object \n 5   Cpu               1273 non-null   object \n 6   Ram               1273 non-null   object \n 7   Memory            1273 non-null   object \n 8   Gpu               1273 non-null   object \n 9   OpSys             1273 non-null   object \n 10  Weight            1273 non-null   object \n 11  Price             1273 non-null   float64\ndtypes: float64(2), object(10)\nmemory usage: 129.3+ KB\n```\n:::\n:::\n\n\nThere are `1273` non-null entries in the dataset now, which means we have successfully removed rows with missing values. Let's check if `Unnamed: 0` column is just an index column or not.\n\n::: {.cell execution_count=6}\n``` {.python .cell-code}\ndf['Unnamed: 0'].nunique()\n```\n\n::: {.cell-output .cell-output-display execution_count=66}\n```\n1273\n```\n:::\n:::\n\n\nIt seems that `Unnamed: 0` column is just an index column, let's drop it as well.\n\n::: {.cell execution_count=7}\n``` {.python .cell-code}\ndf = df.drop(['Unnamed: 0'], axis=1)\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nIndex: 1273 entries, 0 to 1302\nData columns (total 11 columns):\n #   Column            Non-Null Count  Dtype  \n---  ------            --------------  -----  \n 0   Company           1273 non-null   object \n 1   TypeName          1273 non-null   object \n 2   Inches            1273 non-null   object \n 3   ScreenResolution  1273 non-null   object \n 4   Cpu               1273 non-null   object \n 5   Ram               1273 non-null   object \n 6   Memory            1273 non-null   object \n 7   Gpu               1273 non-null   object \n 8   OpSys             1273 non-null   object \n 9   Weight            1273 non-null   object \n 10  Price             1273 non-null   float64\ndtypes: float64(1), object(10)\nmemory usage: 119.3+ KB\n```\n:::\n:::\n\n\nNow we have `1273` non-null entries in the dataset and no missing values. Let's check for duplicates in the data.\n\n::: {.cell execution_count=8}\n``` {.python .cell-code}\nprint(df.duplicated().sum())\n\ndf[df.duplicated()].sort_values(by='Company', ascending=True)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n29\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=68}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Company</th>\n      <th>TypeName</th>\n      <th>Inches</th>\n      <th>ScreenResolution</th>\n      <th>Cpu</th>\n      <th>Ram</th>\n      <th>Memory</th>\n      <th>Gpu</th>\n      <th>OpSys</th>\n      <th>Weight</th>\n      <th>Price</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1291</th>\n      <td>Acer</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Celeron Dual Core N3060 1.6GHz</td>\n      <td>4GB</td>\n      <td>500GB HDD</td>\n      <td>Intel HD Graphics 400</td>\n      <td>Linux</td>\n      <td>2.4kg</td>\n      <td>15397.9200</td>\n    </tr>\n    <tr>\n      <th>1277</th>\n      <td>Acer</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Celeron Dual Core N3060 1.6GHz</td>\n      <td>4GB</td>\n      <td>500GB HDD</td>\n      <td>Intel HD Graphics 400</td>\n      <td>Linux</td>\n      <td>2.4kg</td>\n      <td>15397.9200</td>\n    </tr>\n    <tr>\n      <th>1274</th>\n      <td>Asus</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Celeron Dual Core N3050 1.6GHz</td>\n      <td>4GB</td>\n      <td>500GB HDD</td>\n      <td>Intel HD Graphics</td>\n      <td>Windows 10</td>\n      <td>2.2kg</td>\n      <td>19660.3200</td>\n    </tr>\n    <tr>\n      <th>1297</th>\n      <td>Asus</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Core i7 6500U 2.5GHz</td>\n      <td>4GB</td>\n      <td>500GB HDD</td>\n      <td>Nvidia GeForce 920M</td>\n      <td>Windows 10</td>\n      <td>2.2kg</td>\n      <td>38378.6496</td>\n    </tr>\n    <tr>\n      <th>1289</th>\n      <td>Asus</td>\n      <td>Ultrabook</td>\n      <td>13.3</td>\n      <td>IPS Panel Full HD 1920x1080</td>\n      <td>Intel Core M 6Y30 0.9GHz</td>\n      <td>8GB</td>\n      <td>512GB SSD</td>\n      <td>Intel HD Graphics 515</td>\n      <td>Windows 10</td>\n      <td>1.2kg</td>\n      <td>38841.1200</td>\n    </tr>\n    <tr>\n      <th>1283</th>\n      <td>Asus</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Core i7 6500U 2.5GHz</td>\n      <td>4GB</td>\n      <td>500GB HDD</td>\n      <td>Nvidia GeForce 920M</td>\n      <td>Windows 10</td>\n      <td>2.2kg</td>\n      <td>38378.6496</td>\n    </tr>\n    <tr>\n      <th>1288</th>\n      <td>Asus</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Celeron Dual Core N3050 1.6GHz</td>\n      <td>4GB</td>\n      <td>500GB HDD</td>\n      <td>Intel HD Graphics</td>\n      <td>Windows 10</td>\n      <td>2.2kg</td>\n      <td>19660.3200</td>\n    </tr>\n    <tr>\n      <th>1302</th>\n      <td>Asus</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Celeron Dual Core N3050 1.6GHz</td>\n      <td>4GB</td>\n      <td>500GB HDD</td>\n      <td>Intel HD Graphics</td>\n      <td>Windows 10</td>\n      <td>2.2kg</td>\n      <td>19660.3200</td>\n    </tr>\n    <tr>\n      <th>1275</th>\n      <td>Asus</td>\n      <td>Ultrabook</td>\n      <td>13.3</td>\n      <td>IPS Panel Full HD 1920x1080</td>\n      <td>Intel Core M 6Y30 0.9GHz</td>\n      <td>8GB</td>\n      <td>512GB SSD</td>\n      <td>Intel HD Graphics 515</td>\n      <td>Windows 10</td>\n      <td>1.2kg</td>\n      <td>38841.1200</td>\n    </tr>\n    <tr>\n      <th>1295</th>\n      <td>Dell</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Core i7 7500U 2.7GHz</td>\n      <td>8GB</td>\n      <td>1TB HDD</td>\n      <td>AMD Radeon R5 M430</td>\n      <td>Linux</td>\n      <td>2.3kg</td>\n      <td>42943.1472</td>\n    </tr>\n    <tr>\n      <th>1292</th>\n      <td>Dell</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Celeron Dual Core N3050 1.6GHz</td>\n      <td>2GB</td>\n      <td>500GB HDD</td>\n      <td>Intel HD Graphics</td>\n      <td>Windows 10</td>\n      <td>2.20kg</td>\n      <td>20193.1200</td>\n    </tr>\n    <tr>\n      <th>1290</th>\n      <td>Dell</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Core i3 7100U 2.4GHz</td>\n      <td>6GB</td>\n      <td>1TB HDD</td>\n      <td>Intel HD Graphics 620</td>\n      <td>Windows 10</td>\n      <td>2.3kg</td>\n      <td>24455.5200</td>\n    </tr>\n    <tr>\n      <th>1278</th>\n      <td>Dell</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Celeron Dual Core N3050 1.6GHz</td>\n      <td>2GB</td>\n      <td>500GB HDD</td>\n      <td>Intel HD Graphics</td>\n      <td>Windows 10</td>\n      <td>2.20kg</td>\n      <td>20193.1200</td>\n    </tr>\n    <tr>\n      <th>1281</th>\n      <td>Dell</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Core i7 7500U 2.7GHz</td>\n      <td>8GB</td>\n      <td>1TB HDD</td>\n      <td>AMD Radeon R5 M430</td>\n      <td>Linux</td>\n      <td>2.3kg</td>\n      <td>42943.1472</td>\n    </tr>\n    <tr>\n      <th>1276</th>\n      <td>Dell</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Core i3 7100U 2.4GHz</td>\n      <td>6GB</td>\n      <td>1TB HDD</td>\n      <td>Intel HD Graphics 620</td>\n      <td>Windows 10</td>\n      <td>2.3kg</td>\n      <td>24455.5200</td>\n    </tr>\n    <tr>\n      <th>1301</th>\n      <td>HP</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Core i7 6500U 2.5GHz</td>\n      <td>6GB</td>\n      <td>1TB HDD</td>\n      <td>AMD Radeon R5 M330</td>\n      <td>Windows 10</td>\n      <td>2.19kg</td>\n      <td>40705.9200</td>\n    </tr>\n    <tr>\n      <th>1280</th>\n      <td>HP</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>Full HD 1920x1080</td>\n      <td>AMD A9-Series 9410 2.9GHz</td>\n      <td>6GB</td>\n      <td>1.0TB Hybrid</td>\n      <td>AMD Radeon R7 M440</td>\n      <td>Windows 10</td>\n      <td>2.04kg</td>\n      <td>29303.4672</td>\n    </tr>\n    <tr>\n      <th>1294</th>\n      <td>HP</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>Full HD 1920x1080</td>\n      <td>AMD A9-Series 9410 2.9GHz</td>\n      <td>6GB</td>\n      <td>1.0TB Hybrid</td>\n      <td>AMD Radeon R7 M440</td>\n      <td>Windows 10</td>\n      <td>2.04kg</td>\n      <td>29303.4672</td>\n    </tr>\n    <tr>\n      <th>1296</th>\n      <td>HP</td>\n      <td>Netbook</td>\n      <td>11.6</td>\n      <td>1366x768</td>\n      <td>Intel Celeron Dual Core N3060 1.6GHz</td>\n      <td>2GB</td>\n      <td>32GB Flash Storage</td>\n      <td>Intel HD Graphics 400</td>\n      <td>Windows 10</td>\n      <td>1.17kg</td>\n      <td>11135.5200</td>\n    </tr>\n    <tr>\n      <th>1282</th>\n      <td>HP</td>\n      <td>Netbook</td>\n      <td>11.6</td>\n      <td>1366x768</td>\n      <td>Intel Celeron Dual Core N3060 1.6GHz</td>\n      <td>2GB</td>\n      <td>32GB Flash Storage</td>\n      <td>Intel HD Graphics 400</td>\n      <td>Windows 10</td>\n      <td>1.17kg</td>\n      <td>11135.5200</td>\n    </tr>\n    <tr>\n      <th>1287</th>\n      <td>HP</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>1366x768</td>\n      <td>Intel Core i7 6500U 2.5GHz</td>\n      <td>6GB</td>\n      <td>1TB HDD</td>\n      <td>AMD Radeon R5 M330</td>\n      <td>Windows 10</td>\n      <td>2.19kg</td>\n      <td>40705.9200</td>\n    </tr>\n    <tr>\n      <th>1286</th>\n      <td>Lenovo</td>\n      <td>Notebook</td>\n      <td>14</td>\n      <td>1366x768</td>\n      <td>Intel Celeron Dual Core N3050 1.6GHz</td>\n      <td>2GB</td>\n      <td>64GB Flash Storage</td>\n      <td>Intel HD Graphics</td>\n      <td>Windows 10</td>\n      <td>1.5kg</td>\n      <td>12201.1200</td>\n    </tr>\n    <tr>\n      <th>1285</th>\n      <td>Lenovo</td>\n      <td>2 in 1 Convertible</td>\n      <td>13.3</td>\n      <td>IPS Panel Quad HD+ / Touchscreen 3200x1800</td>\n      <td>Intel Core i7 6500U 2.5GHz</td>\n      <td>16GB</td>\n      <td>512GB SSD</td>\n      <td>Intel HD Graphics 520</td>\n      <td>Windows 10</td>\n      <td>1.3kg</td>\n      <td>79866.7200</td>\n    </tr>\n    <tr>\n      <th>1284</th>\n      <td>Lenovo</td>\n      <td>2 in 1 Convertible</td>\n      <td>14</td>\n      <td>IPS Panel Full HD / Touchscreen 1920x1080</td>\n      <td>Intel Core i7 6500U 2.5GHz</td>\n      <td>4GB</td>\n      <td>128GB SSD</td>\n      <td>Intel HD Graphics 520</td>\n      <td>Windows 10</td>\n      <td>1.8kg</td>\n      <td>33992.6400</td>\n    </tr>\n    <tr>\n      <th>1293</th>\n      <td>Lenovo</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>IPS Panel Full HD 1920x1080</td>\n      <td>Intel Core i7 6700HQ 2.6GHz</td>\n      <td>8GB</td>\n      <td>1TB HDD</td>\n      <td>Nvidia GeForce GTX 960M</td>\n      <td>Windows 10</td>\n      <td>2.6kg</td>\n      <td>47898.7200</td>\n    </tr>\n    <tr>\n      <th>1279</th>\n      <td>Lenovo</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>IPS Panel Full HD 1920x1080</td>\n      <td>Intel Core i7 6700HQ 2.6GHz</td>\n      <td>8GB</td>\n      <td>1TB HDD</td>\n      <td>Nvidia GeForce GTX 960M</td>\n      <td>Windows 10</td>\n      <td>2.6kg</td>\n      <td>47898.7200</td>\n    </tr>\n    <tr>\n      <th>1298</th>\n      <td>Lenovo</td>\n      <td>2 in 1 Convertible</td>\n      <td>14</td>\n      <td>IPS Panel Full HD / Touchscreen 1920x1080</td>\n      <td>Intel Core i7 6500U 2.5GHz</td>\n      <td>4GB</td>\n      <td>128GB SSD</td>\n      <td>Intel HD Graphics 520</td>\n      <td>Windows 10</td>\n      <td>1.8kg</td>\n      <td>33992.6400</td>\n    </tr>\n    <tr>\n      <th>1299</th>\n      <td>Lenovo</td>\n      <td>2 in 1 Convertible</td>\n      <td>13.3</td>\n      <td>IPS Panel Quad HD+ / Touchscreen 3200x1800</td>\n      <td>Intel Core i7 6500U 2.5GHz</td>\n      <td>16GB</td>\n      <td>512GB SSD</td>\n      <td>Intel HD Graphics 520</td>\n      <td>Windows 10</td>\n      <td>1.3kg</td>\n      <td>79866.7200</td>\n    </tr>\n    <tr>\n      <th>1300</th>\n      <td>Lenovo</td>\n      <td>Notebook</td>\n      <td>14</td>\n      <td>1366x768</td>\n      <td>Intel Celeron Dual Core N3050 1.6GHz</td>\n      <td>2GB</td>\n      <td>64GB Flash Storage</td>\n      <td>Intel HD Graphics</td>\n      <td>Windows 10</td>\n      <td>1.5kg</td>\n      <td>12201.1200</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThere are 29 duplicate records in the dataset, let's drop them.\n\n::: {.cell execution_count=9}\n``` {.python .cell-code}\ndf = df.drop_duplicates()\n\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nIndex: 1244 entries, 0 to 1273\nData columns (total 11 columns):\n #   Column            Non-Null Count  Dtype  \n---  ------            --------------  -----  \n 0   Company           1244 non-null   object \n 1   TypeName          1244 non-null   object \n 2   Inches            1244 non-null   object \n 3   ScreenResolution  1244 non-null   object \n 4   Cpu               1244 non-null   object \n 5   Ram               1244 non-null   object \n 6   Memory            1244 non-null   object \n 7   Gpu               1244 non-null   object \n 8   OpSys             1244 non-null   object \n 9   Weight            1244 non-null   object \n 10  Price             1244 non-null   float64\ndtypes: float64(1), object(10)\nmemory usage: 116.6+ KB\n```\n:::\n:::\n\n\nNow we have `1244` non-null entries in the dataset and no missing values or duplicates.\n\nThere are 11 columns in the dataset, among which `Price` is the only column with `folat64` data type rest are `object` data type.\n\n## Exploratory Data Analysis\n\nLet's start with the basic statistics of the dataset.\n\n::: {.cell execution_count=10}\n``` {.python .cell-code}\ndf.describe(include='all')\n```\n\n::: {.cell-output .cell-output-display execution_count=70}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Company</th>\n      <th>TypeName</th>\n      <th>Inches</th>\n      <th>ScreenResolution</th>\n      <th>Cpu</th>\n      <th>Ram</th>\n      <th>Memory</th>\n      <th>Gpu</th>\n      <th>OpSys</th>\n      <th>Weight</th>\n      <th>Price</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>1244</td>\n      <td>1244</td>\n      <td>1244</td>\n      <td>1244</td>\n      <td>1244</td>\n      <td>1244</td>\n      <td>1244</td>\n      <td>1244</td>\n      <td>1244</td>\n      <td>1244</td>\n      <td>1244.000000</td>\n    </tr>\n    <tr>\n      <th>unique</th>\n      <td>19</td>\n      <td>6</td>\n      <td>25</td>\n      <td>40</td>\n      <td>118</td>\n      <td>10</td>\n      <td>40</td>\n      <td>110</td>\n      <td>9</td>\n      <td>189</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>top</th>\n      <td>Lenovo</td>\n      <td>Notebook</td>\n      <td>15.6</td>\n      <td>Full HD 1920x1080</td>\n      <td>Intel Core i5 7200U 2.5GHz</td>\n      <td>8GB</td>\n      <td>256GB SSD</td>\n      <td>Intel HD Graphics 620</td>\n      <td>Windows 10</td>\n      <td>2.2kg</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>freq</th>\n      <td>282</td>\n      <td>689</td>\n      <td>621</td>\n      <td>493</td>\n      <td>183</td>\n      <td>595</td>\n      <td>401</td>\n      <td>269</td>\n      <td>1022</td>\n      <td>106</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>60606.224427</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>37424.636161</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>9270.720000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>32655.445200</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>52693.920000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>79813.440000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>324954.720000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe dataset contains 11 columns with the following features: - **Company**: The brand of the laptop with 19 brands. - **TypeName**: The type of laptop, such as Ultrabook, Gaming, etc. - **Inches**: The size of the laptop screen in inches. - **ScreenResolution**: The resolution of the laptop screen. - **Cpu**: The type of CPU used in the laptop. - **Ram**: The amount of RAM in GB. - **Memory**: The type and size of storage memory (HDD/SSD). - **Gpu**: The type of GPU used in the laptop. - **OpSys**: The operating system installed on the laptop. - **Weight**: The weight of the laptop in kg. - **Price**: The price of the laptop in INR(Indian Rupees).\n\n### Feature Extraction\n\nLet's extract some features from the existing columns to make the dataset more informative.\n\nFirst lets convert all the column names to lower case for consistency.\n\n::: {.cell execution_count=11}\n``` {.python .cell-code}\ndf.columns = df.columns.str.lower()\n\nprint(df.columns)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIndex(['company', 'typename', 'inches', 'screenresolution', 'cpu', 'ram',\n       'memory', 'gpu', 'opsys', 'weight', 'price'],\n      dtype='object')\n```\n:::\n:::\n\n\nLet's check for the unique values in columns.\n\n::: {.cell execution_count=12}\n``` {.python .cell-code}\nprint(df.company.unique())\nprint(df.typename.unique())\nprint(df.ram.unique())\nprint(df.opsys.unique())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n['Apple' 'HP' 'Acer' 'Asus' 'Dell' 'Lenovo' 'Chuwi' 'MSI' 'Microsoft'\n 'Toshiba' 'Huawei' 'Xiaomi' 'Vero' 'Razer' 'Mediacom' 'Samsung' 'Google'\n 'Fujitsu' 'LG']\n['Ultrabook' 'Notebook' 'Gaming' '2 in 1 Convertible' 'Workstation'\n 'Netbook']\n['8GB' '16GB' '4GB' '2GB' '12GB' '64GB' '6GB' '32GB' '24GB' '1GB']\n['macOS' 'No OS' 'Windows 10' 'Mac OS X' 'Linux' 'Windows 10 S'\n 'Chrome OS' 'Windows 7' 'Android']\n```\n:::\n:::\n\n\n::: {.cell execution_count=13}\n``` {.python .cell-code}\nprint(df.cpu[1])\nprint(df.screenresolution[6])\nprint(df.gpu[88])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIntel Core i5 1.8GHz\nIPS Panel Retina Display 2880x1800\nNvidia GeForce GTX 1060\n```\n:::\n:::\n\n\nwe can seperate values in columns to form new parameters i.e, - `screenresolution` can give us `display_type`, `resolution` & `touchscreen` - `cpu` can be seperated to form `cpu` and `clockspeed` - `memory` can be seperated to form `memory` and `memory_type` - `gpu` can be seperated to get `gpu_company`\n\n#### `CPU` features\n\n::: {.cell execution_count=14}\n``` {.python .cell-code}\n# cpu brand name\ndf['cpu_brand'] = df.cpu.str.split().str[0]\n\n# cpu name\ndf['cpu_name'] = df.cpu.str.replace(r'\\d+(?:\\.\\d+)?GHz', '', regex=True,).str.strip()\n# removing brand name\ndf['cpu_name'] = df.cpu_name.str.replace(r'^\\w+', '', regex=True).str.strip()\n\n# cpu clock speed\ndf['cpu_ghz'] = df.cpu.str.extract(r'(\\d+(?:\\.\\d+)?)GHz').astype('float64')\n\ndf[['cpu_brand', 'cpu_name', 'cpu_ghz']]\n```\n\n::: {.cell-output .cell-output-display execution_count=74}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>cpu_brand</th>\n      <th>cpu_name</th>\n      <th>cpu_ghz</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Intel</td>\n      <td>Core i5</td>\n      <td>2.3</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Intel</td>\n      <td>Core i5</td>\n      <td>1.8</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Intel</td>\n      <td>Core i5 7200U</td>\n      <td>2.5</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Intel</td>\n      <td>Core i7</td>\n      <td>2.7</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Intel</td>\n      <td>Core i5</td>\n      <td>3.1</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>1269</th>\n      <td>Intel</td>\n      <td>Core i7 6500U</td>\n      <td>2.5</td>\n    </tr>\n    <tr>\n      <th>1270</th>\n      <td>Intel</td>\n      <td>Core i7 6500U</td>\n      <td>2.5</td>\n    </tr>\n    <tr>\n      <th>1271</th>\n      <td>Intel</td>\n      <td>Core i7 6500U</td>\n      <td>2.5</td>\n    </tr>\n    <tr>\n      <th>1272</th>\n      <td>Intel</td>\n      <td>Celeron Dual Core N3050</td>\n      <td>1.6</td>\n    </tr>\n    <tr>\n      <th>1273</th>\n      <td>Intel</td>\n      <td>Core i7 6500U</td>\n      <td>2.5</td>\n    </tr>\n  </tbody>\n</table>\n<p>1244 rows × 3 columns</p>\n</div>\n```\n:::\n:::\n\n\nNow, we have 3 columns act as seperate features for the price prediction.\n\n#### `Screen Resolution` Features\n\n-   `screenresolution` has many features ie., screen type, screen height, width, touch screen etc. Let's extract all of them\n\n::: {.cell execution_count=15}\n``` {.python .cell-code}\n# display resolution\ndf['resolution'] = df['screenresolution'].str.extract(r'(\\d+x\\d+)')\n\n# touch screen or not\ndf['touchscreen'] = df['screenresolution'].apply(lambda x: 1 if 'Touchscreen' in x else 0)\n\n# Display type\ndf['display_type'] = df['screenresolution'].str.replace(r'\\d+x\\d+', \"\", regex = True).str.strip()\n\ndf['display_type'] = df['display_type'].str.replace(r'(Full HD|Quad HD|4K Ultra HD|/|\\+|Touchscreen)', '', regex = True).str.replace('/', '', regex = True).str.strip()\n\ndf[['resolution', 'touchscreen', 'display_type']]\n```\n\n::: {.cell-output .cell-output-display execution_count=75}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>resolution</th>\n      <th>touchscreen</th>\n      <th>display_type</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2560x1600</td>\n      <td>0</td>\n      <td>IPS Panel Retina Display</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1440x900</td>\n      <td>0</td>\n      <td></td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1920x1080</td>\n      <td>0</td>\n      <td></td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2880x1800</td>\n      <td>0</td>\n      <td>IPS Panel Retina Display</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2560x1600</td>\n      <td>0</td>\n      <td>IPS Panel Retina Display</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>1269</th>\n      <td>1366x768</td>\n      <td>0</td>\n      <td></td>\n    </tr>\n    <tr>\n      <th>1270</th>\n      <td>1920x1080</td>\n      <td>1</td>\n      <td>IPS Panel</td>\n    </tr>\n    <tr>\n      <th>1271</th>\n      <td>3200x1800</td>\n      <td>1</td>\n      <td>IPS Panel</td>\n    </tr>\n    <tr>\n      <th>1272</th>\n      <td>1366x768</td>\n      <td>0</td>\n      <td></td>\n    </tr>\n    <tr>\n      <th>1273</th>\n      <td>1366x768</td>\n      <td>0</td>\n      <td></td>\n    </tr>\n  </tbody>\n</table>\n<p>1244 rows × 3 columns</p>\n</div>\n```\n:::\n:::\n\n\nNow, we have another 3 columns to act as 3 seperate features.\n\n::: {.cell execution_count=16}\n``` {.python .cell-code}\ndf.touchscreen.sum()\n```\n\n::: {.cell-output .cell-output-display execution_count=76}\n```\nnp.int64(181)\n```\n:::\n:::\n\n\n#### `GPU` Features\n\nLet's extarct `gpu_brand` and `gpu_name` from the column `gpu`\n\n::: {.cell execution_count=17}\n``` {.python .cell-code}\n# gpu brand\ndf['gpu_brand'] = df['gpu'].str.extract(r'^(\\w+)')\n\n# gpu name\ndf['gpu_name'] = df['gpu'].str.replace(r'^(\\w+)', '', regex = True).str.strip()\n\ndf[['gpu_brand', 'gpu_name']]\n\n```\n\n::: {.cell-output .cell-output-display execution_count=77}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>gpu_brand</th>\n      <th>gpu_name</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Intel</td>\n      <td>Iris Plus Graphics 640</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Intel</td>\n      <td>HD Graphics 6000</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Intel</td>\n      <td>HD Graphics 620</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>AMD</td>\n      <td>Radeon Pro 455</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Intel</td>\n      <td>Iris Plus Graphics 650</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>1269</th>\n      <td>Nvidia</td>\n      <td>GeForce 920M</td>\n    </tr>\n    <tr>\n      <th>1270</th>\n      <td>Intel</td>\n      <td>HD Graphics 520</td>\n    </tr>\n    <tr>\n      <th>1271</th>\n      <td>Intel</td>\n      <td>HD Graphics 520</td>\n    </tr>\n    <tr>\n      <th>1272</th>\n      <td>Intel</td>\n      <td>HD Graphics</td>\n    </tr>\n    <tr>\n      <th>1273</th>\n      <td>AMD</td>\n      <td>Radeon R5 M330</td>\n    </tr>\n  </tbody>\n</table>\n<p>1244 rows × 2 columns</p>\n</div>\n```\n:::\n:::\n\n\n#### `Memory Features` Features\n\nMost of the laptops have two drives which need to be seperated and type of memory is also in the memory so we need to seperate them both after seperating the drives.\n\n-   First replace the `TB` with `GB`(1TB \\~ 1000GB)\n-   `+` seperates two drives, `str.split()` function can be used to list the two memory drives and then they are slotted into seperate columns.\n\n::: {.cell execution_count=18}\n``` {.python .cell-code}\ndf.memory = df.memory.str.replace(r'1.0TB|1TB', \"1000GB\", regex = True)\ndf.memory = df.memory.str.replace(r'2.0TB|2TB', \"2000GB\", regex = True)\n\ndf.memory.unique()\n```\n\n::: {.cell-output .cell-output-display execution_count=78}\n```\narray(['128GB SSD', '128GB Flash Storage', '256GB SSD', '512GB SSD',\n       '500GB HDD', '256GB Flash Storage', '1000GB HDD',\n       '128GB SSD +  1000GB HDD', '256GB SSD +  256GB SSD',\n       '64GB Flash Storage', '32GB Flash Storage',\n       '256GB SSD +  1000GB HDD', '256GB SSD +  2000GB HDD', '32GB SSD',\n       '2000GB HDD', '64GB SSD', '1000GB Hybrid',\n       '512GB SSD +  1000GB HDD', '1000GB SSD', '256GB SSD +  500GB HDD',\n       '128GB SSD +  2000GB HDD', '512GB SSD +  512GB SSD', '16GB SSD',\n       '16GB Flash Storage', '512GB SSD +  256GB SSD',\n       '512GB SSD +  2000GB HDD', '64GB Flash Storage +  1000GB HDD',\n       '180GB SSD', '1000GB HDD +  1000GB HDD', '32GB HDD',\n       '1000GB SSD +  1000GB HDD', '?', '512GB Flash Storage',\n       '128GB HDD', '240GB SSD', '8GB SSD', '508GB Hybrid',\n       '512GB SSD +  1000GB Hybrid', '256GB SSD +  1000GB Hybrid'],\n      dtype=object)\n```\n:::\n:::\n\n\n::: {.cell execution_count=19}\n``` {.python .cell-code}\ndf['memory_list'] = df.memory.str.split('+')\n\ndf['memory_1'] = df['memory_list'].str[0]\ndf['memory_2'] = df['memory_list'].str[1]\n\ndf[['memory_1', 'memory_2']]\n```\n\n::: {.cell-output .cell-output-display execution_count=79}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>memory_1</th>\n      <th>memory_2</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>128GB SSD</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>128GB Flash Storage</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>256GB SSD</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>512GB SSD</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>256GB SSD</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>1269</th>\n      <td>500GB HDD</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1270</th>\n      <td>128GB SSD</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1271</th>\n      <td>512GB SSD</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1272</th>\n      <td>64GB Flash Storage</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1273</th>\n      <td>1000GB HDD</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>\n<p>1244 rows × 2 columns</p>\n</div>\n```\n:::\n:::\n\n\nLet's seperate `df['memory_1']` into 2 seperate columns for `memory_capacity` and `memory_type`\n\n::: {.cell execution_count=20}\n``` {.python .cell-code}\ndf['memory_capacity_1'] = df['memory_1'].str.extract(r'(\\d+)').astype('float64')\ndf['memory_type_1'] = df['memory_1'].str.replace(r'(\\d+[A-Z]{2})', '', regex = True).str.strip()\n\ndf[['memory_capacity_1', 'memory_type_1']]\n```\n\n::: {.cell-output .cell-output-display execution_count=80}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>memory_capacity_1</th>\n      <th>memory_type_1</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>128.0</td>\n      <td>SSD</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>128.0</td>\n      <td>Flash Storage</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>256.0</td>\n      <td>SSD</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>512.0</td>\n      <td>SSD</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>256.0</td>\n      <td>SSD</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>1269</th>\n      <td>500.0</td>\n      <td>HDD</td>\n    </tr>\n    <tr>\n      <th>1270</th>\n      <td>128.0</td>\n      <td>SSD</td>\n    </tr>\n    <tr>\n      <th>1271</th>\n      <td>512.0</td>\n      <td>SSD</td>\n    </tr>\n    <tr>\n      <th>1272</th>\n      <td>64.0</td>\n      <td>Flash Storage</td>\n    </tr>\n    <tr>\n      <th>1273</th>\n      <td>1000.0</td>\n      <td>HDD</td>\n    </tr>\n  </tbody>\n</table>\n<p>1244 rows × 2 columns</p>\n</div>\n```\n:::\n:::\n\n\nLet's repeat this for `memory_2` also\n\n::: {.cell execution_count=21}\n``` {.python .cell-code}\ndf['memory_capacity_2'] = df['memory_2'].str.extract(r'(\\d+)').astype('float64')\ndf['memory_type_2'] = df['memory_2'].str.replace(r'(\\d+[A-Z]{2})', '', regex = True).str.strip()\n\ndf[['memory_capacity_2', 'memory_type_2']].dropna()\n```\n\n::: {.cell-output .cell-output-display execution_count=81}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>memory_capacity_2</th>\n      <th>memory_type_2</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>21</th>\n      <td>1000.0</td>\n      <td>HDD</td>\n    </tr>\n    <tr>\n      <th>28</th>\n      <td>256.0</td>\n      <td>SSD</td>\n    </tr>\n    <tr>\n      <th>37</th>\n      <td>1000.0</td>\n      <td>HDD</td>\n    </tr>\n    <tr>\n      <th>41</th>\n      <td>1000.0</td>\n      <td>HDD</td>\n    </tr>\n    <tr>\n      <th>47</th>\n      <td>1000.0</td>\n      <td>HDD</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>1233</th>\n      <td>1000.0</td>\n      <td>HDD</td>\n    </tr>\n    <tr>\n      <th>1238</th>\n      <td>1000.0</td>\n      <td>HDD</td>\n    </tr>\n    <tr>\n      <th>1247</th>\n      <td>1000.0</td>\n      <td>HDD</td>\n    </tr>\n    <tr>\n      <th>1256</th>\n      <td>1000.0</td>\n      <td>HDD</td>\n    </tr>\n    <tr>\n      <th>1259</th>\n      <td>1000.0</td>\n      <td>HDD</td>\n    </tr>\n  </tbody>\n</table>\n<p>204 rows × 2 columns</p>\n</div>\n```\n:::\n:::\n\n\n#### Other Features\n\nLet's convert all the columns that can be numeric into numeric or float i.e, `ram`, `inches`, `weight`\n\n::: {.cell execution_count=22}\n``` {.python .cell-code}\ndf['ram_gb'] = df['ram'].str.replace('GB', '').astype('int')\n\ndf['inches_size'] = pd.to_numeric(df['inches'], errors= 'coerce')\n\ndf['weight_kg'] = df['weight'].replace('?', np.nan).str.replace('kg', '').astype('float64')\n\ndf[['ram_gb', 'inches_size', 'weight_kg']]\n```\n\n::: {.cell-output .cell-output-display execution_count=82}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>ram_gb</th>\n      <th>inches_size</th>\n      <th>weight_kg</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>8</td>\n      <td>13.3</td>\n      <td>1.37</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>8</td>\n      <td>13.3</td>\n      <td>1.34</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>8</td>\n      <td>15.6</td>\n      <td>1.86</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>16</td>\n      <td>15.4</td>\n      <td>1.83</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>8</td>\n      <td>13.3</td>\n      <td>1.37</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>1269</th>\n      <td>4</td>\n      <td>15.6</td>\n      <td>2.20</td>\n    </tr>\n    <tr>\n      <th>1270</th>\n      <td>4</td>\n      <td>14.0</td>\n      <td>1.80</td>\n    </tr>\n    <tr>\n      <th>1271</th>\n      <td>16</td>\n      <td>13.3</td>\n      <td>1.30</td>\n    </tr>\n    <tr>\n      <th>1272</th>\n      <td>2</td>\n      <td>14.0</td>\n      <td>1.50</td>\n    </tr>\n    <tr>\n      <th>1273</th>\n      <td>6</td>\n      <td>15.6</td>\n      <td>2.19</td>\n    </tr>\n  </tbody>\n</table>\n<p>1244 rows × 3 columns</p>\n</div>\n```\n:::\n:::\n\n\nLet's look at data once more\n\n::: {.cell execution_count=23}\n``` {.python .cell-code}\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nIndex: 1244 entries, 0 to 1273\nData columns (total 29 columns):\n #   Column             Non-Null Count  Dtype  \n---  ------             --------------  -----  \n 0   company            1244 non-null   object \n 1   typename           1244 non-null   object \n 2   inches             1244 non-null   object \n 3   screenresolution   1244 non-null   object \n 4   cpu                1244 non-null   object \n 5   ram                1244 non-null   object \n 6   memory             1244 non-null   object \n 7   gpu                1244 non-null   object \n 8   opsys              1244 non-null   object \n 9   weight             1244 non-null   object \n 10  price              1244 non-null   float64\n 11  cpu_brand          1244 non-null   object \n 12  cpu_name           1244 non-null   object \n 13  cpu_ghz            1244 non-null   float64\n 14  resolution         1244 non-null   object \n 15  touchscreen        1244 non-null   int64  \n 16  display_type       1244 non-null   object \n 17  gpu_brand          1244 non-null   object \n 18  gpu_name           1244 non-null   object \n 19  memory_list        1244 non-null   object \n 20  memory_1           1244 non-null   object \n 21  memory_2           204 non-null    object \n 22  memory_capacity_1  1243 non-null   float64\n 23  memory_type_1      1244 non-null   object \n 24  memory_capacity_2  204 non-null    float64\n 25  memory_type_2      204 non-null    object \n 26  ram_gb             1244 non-null   int64  \n 27  inches_size        1243 non-null   float64\n 28  weight_kg          1243 non-null   float64\ndtypes: float64(6), int64(2), object(21)\nmemory usage: 323.9+ KB\n```\n:::\n:::\n\n\n`11` columns just were made into 29 columns among which repeated columns are not necessary to build a model so let's remove them.\n\n::: {.cell execution_count=24}\n``` {.python .cell-code}\ndf_clean = df.drop(columns = ['ram','screenresolution', 'cpu', 'memory', 'memory_list',\n                              'memory_1', 'memory_2' ,'gpu', 'weight', 'inches'])\n\nprint(df_clean.info())\ndf_clean.head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nIndex: 1244 entries, 0 to 1273\nData columns (total 19 columns):\n #   Column             Non-Null Count  Dtype  \n---  ------             --------------  -----  \n 0   company            1244 non-null   object \n 1   typename           1244 non-null   object \n 2   opsys              1244 non-null   object \n 3   price              1244 non-null   float64\n 4   cpu_brand          1244 non-null   object \n 5   cpu_name           1244 non-null   object \n 6   cpu_ghz            1244 non-null   float64\n 7   resolution         1244 non-null   object \n 8   touchscreen        1244 non-null   int64  \n 9   display_type       1244 non-null   object \n 10  gpu_brand          1244 non-null   object \n 11  gpu_name           1244 non-null   object \n 12  memory_capacity_1  1243 non-null   float64\n 13  memory_type_1      1244 non-null   object \n 14  memory_capacity_2  204 non-null    float64\n 15  memory_type_2      204 non-null    object \n 16  ram_gb             1244 non-null   int64  \n 17  inches_size        1243 non-null   float64\n 18  weight_kg          1243 non-null   float64\ndtypes: float64(6), int64(2), object(11)\nmemory usage: 226.7+ KB\nNone\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=84}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>company</th>\n      <th>typename</th>\n      <th>opsys</th>\n      <th>price</th>\n      <th>cpu_brand</th>\n      <th>cpu_name</th>\n      <th>cpu_ghz</th>\n      <th>resolution</th>\n      <th>touchscreen</th>\n      <th>display_type</th>\n      <th>gpu_brand</th>\n      <th>gpu_name</th>\n      <th>memory_capacity_1</th>\n      <th>memory_type_1</th>\n      <th>memory_capacity_2</th>\n      <th>memory_type_2</th>\n      <th>ram_gb</th>\n      <th>inches_size</th>\n      <th>weight_kg</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>macOS</td>\n      <td>71378.6832</td>\n      <td>Intel</td>\n      <td>Core i5</td>\n      <td>2.3</td>\n      <td>2560x1600</td>\n      <td>0</td>\n      <td>IPS Panel Retina Display</td>\n      <td>Intel</td>\n      <td>Iris Plus Graphics 640</td>\n      <td>128.0</td>\n      <td>SSD</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>8</td>\n      <td>13.3</td>\n      <td>1.37</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>macOS</td>\n      <td>47895.5232</td>\n      <td>Intel</td>\n      <td>Core i5</td>\n      <td>1.8</td>\n      <td>1440x900</td>\n      <td>0</td>\n      <td></td>\n      <td>Intel</td>\n      <td>HD Graphics 6000</td>\n      <td>128.0</td>\n      <td>Flash Storage</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>8</td>\n      <td>13.3</td>\n      <td>1.34</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>HP</td>\n      <td>Notebook</td>\n      <td>No OS</td>\n      <td>30636.0000</td>\n      <td>Intel</td>\n      <td>Core i5 7200U</td>\n      <td>2.5</td>\n      <td>1920x1080</td>\n      <td>0</td>\n      <td></td>\n      <td>Intel</td>\n      <td>HD Graphics 620</td>\n      <td>256.0</td>\n      <td>SSD</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>8</td>\n      <td>15.6</td>\n      <td>1.86</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>macOS</td>\n      <td>135195.3360</td>\n      <td>Intel</td>\n      <td>Core i7</td>\n      <td>2.7</td>\n      <td>2880x1800</td>\n      <td>0</td>\n      <td>IPS Panel Retina Display</td>\n      <td>AMD</td>\n      <td>Radeon Pro 455</td>\n      <td>512.0</td>\n      <td>SSD</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>16</td>\n      <td>15.4</td>\n      <td>1.83</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>macOS</td>\n      <td>96095.8080</td>\n      <td>Intel</td>\n      <td>Core i5</td>\n      <td>3.1</td>\n      <td>2560x1600</td>\n      <td>0</td>\n      <td>IPS Panel Retina Display</td>\n      <td>Intel</td>\n      <td>Iris Plus Graphics 650</td>\n      <td>256.0</td>\n      <td>SSD</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>8</td>\n      <td>13.3</td>\n      <td>1.37</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nNow that dataset is clean let's go for EDA.\n\n### Data Visualisation\n\nAs we have 8 numeric columns, let's start with correlation plot.\n\n::: {.cell execution_count=25}\n``` {.python .cell-code}\nsns.heatmap(df_clean.select_dtypes(include = ['int64', 'float64']).corr(),\n                                   annot = True, cmap = 'coolwarm')\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](laptop_price_prediction_files/figure-docx/cell-26-output-1.png){}\n:::\n:::\n\n\nWe can see that `price` has a strong positive correlation with `ram_gb` and `cpu_ghz`.\n\nLet's check the distribution of `price` column.\n\n::: {.cell execution_count=26}\n``` {.python .cell-code}\nsns.histplot(df_clean['price'], bins = 20, kde = True)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](laptop_price_prediction_files/figure-docx/cell-27-output-1.png){}\n:::\n:::\n\n\nThe plot is right skewed, we can `log` transform the `price` column to make it more normal.\n\n::: {.cell execution_count=27}\n``` {.python .cell-code}\ndf_clean['price_log'] = np.log1p(df_clean['price'])\n\nsns.histplot(df_clean['price_log'], bins = 50, kde = True)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](laptop_price_prediction_files/figure-docx/cell-28-output-1.png){}\n:::\n:::\n\n\n`price_log` is more normally distributed, let's check the correlation of `price_log` with other columns.\n\n::: {.cell execution_count=28}\n``` {.python .cell-code}\nsns.heatmap(df_clean.drop(columns = ['price']).select_dtypes(include = ['int64', 'float64']).corr(),\n                                    annot = True, cmap = 'coolwarm')\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](laptop_price_prediction_files/figure-docx/cell-29-output-1.png){}\n:::\n:::\n\n\nWe can see that `price_log` has a strong positive correlation with `ram_gb` and `cpu_ghz`.\n\nLet's plot `price_log` in a boxplot to get the outliers.\n\n::: {.cell execution_count=29}\n``` {.python .cell-code}\nax = sns.boxplot(x='price_log', data=df_clean)\nmax = df_clean['price_log'].max()\nplt.text(max, 0, f'{max:.2f}', ha='center', va='bottom', color='red')\nplt.xlabel('Price_log')\nplt.title('Boxplot of Price_log')\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](laptop_price_prediction_files/figure-docx/cell-30-output-1.png){}\n:::\n:::\n\n\nThere is only one outlier in the data, let's remove it.\n\n::: {.cell execution_count=30}\n``` {.python .cell-code}\ndf_clean = df_clean[df_clean['price_log'] < 12.6]\n\ndf_clean['price_log'].max()\n```\n\n::: {.cell-output .cell-output-display execution_count=90}\n```\nnp.float64(12.587885975858104)\n```\n:::\n:::\n\n\nNow we have removed the outliers from `price_log` column. Let's look at `object` columns starting with companies.\n\n::: {.cell execution_count=31}\n``` {.python .cell-code}\nsns.barplot(x = df_clean.company.value_counts().index,\n            y = df_clean.company.value_counts().values)\nplt.xlabel('Company')\nplt.ylabel('Count')\nplt.title('Company Counts')\nplt.xticks(rotation = 90)\nplt.show()\n\n```\n\n::: {.cell-output .cell-output-display}\n![](laptop_price_prediction_files/figure-docx/cell-32-output-1.png){}\n:::\n:::\n\n\n**Lenovo**, **Dell**, **HP** are the top 3 companies in the dataset.\n\n::: {.cell execution_count=32}\n``` {.python .cell-code}\ncompany_counts = df_clean.company.value_counts()\n\nprint((company_counts[:3].sum()/len(df_clean)).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0.662\n```\n:::\n:::\n\n\n**66.2%** of the laptops are from **Lenovo**, **Dell**, **HP**.\n\nLet's look at `cpu` and it's features.\n\n::: {.cell execution_count=33}\n``` {.python .cell-code}\nprint(df_clean.cpu_brand.nunique())\nprint(df_clean.cpu_ghz.nunique())\nprint(df_clean.cpu_name.nunique())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n3\n25\n93\n```\n:::\n:::\n\n\nThere are 3 unique values in `cpu_brand`, 25 unique values in `cpu_ghz`, 93 unique values in `cpu_name`.\n\n::: {.cell execution_count=34}\n``` {.python .cell-code}\ncpu_brand_counts = df_clean.cpu_brand.value_counts()\ncpu_ghz_counts = df_clean.cpu_ghz.value_counts().sort_values(ascending = False)\ncpu_name_counts = df_clean.cpu_name.value_counts()\n\nprint(cpu_brand_counts)\nprint(cpu_ghz_counts)\n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncpu_brand\nIntel      1182\nAMD          60\nSamsung       1\nName: count, dtype: int64\ncpu_ghz\n2.50    278\n2.80    161\n2.70    158\n1.60    118\n2.30     84\n2.00     84\n1.80     77\n2.60     73\n1.10     53\n2.40     50\n3.00     19\n2.90     18\n1.20     15\n2.20     11\n1.44     10\n1.50     10\n1.30      6\n3.60      5\n3.10      3\n2.10      3\n1.90      2\n0.90      2\n3.20      1\n1.00      1\n1.92      1\nName: count, dtype: int64\n```\n:::\n:::\n\n\nMost of the laptops have `Intel` CPU, `2.4GHz` is the most common CPU clock speed, `Intel Core i5` is the most common CPU name.\n\n`Samsung` has only one laptop in the dataset, which is not ideal for building a model, let's remove it.\n\n::: {.cell execution_count=35}\n``` {.python .cell-code}\ndf_clean = df_clean[df_clean.cpu_brand != 'Samsung']\n\ndf_clean.cpu_brand.unique()\n```\n\n::: {.cell-output .cell-output-display execution_count=95}\n```\narray(['Intel', 'AMD'], dtype=object)\n```\n:::\n:::\n\n\nLet's plot `cpu_ghz` to know the distribution of CPU clock speed.\n\n::: {.cell execution_count=36}\n``` {.python .cell-code}\nsns.barplot(x=cpu_ghz_counts.index.astype(str),\n            y=cpu_ghz_counts.values)\nplt.xlabel('CPU GHz')\nplt.ylabel('Count')\nplt.title('CPU GHz Distribution')\nplt.xticks(rotation=90)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](laptop_price_prediction_files/figure-docx/cell-37-output-1.png){}\n:::\n:::\n\n\n`2.5GHz` is the most common CPU clock speed, followed by `2.8GHz` and `2.7GHz`.\n\n::: {.cell execution_count=37}\n``` {.python .cell-code}\nsns.barplot(x=df_clean.inches_size.value_counts().index.astype(str),\n            y=df_clean.inches_size.value_counts().values)\nplt.xlabel('Screen Size')\nplt.ylabel('Count')\nplt.xticks(rotation=90)\nplt.title('Laptops with screen sizes')\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](laptop_price_prediction_files/figure-docx/cell-38-output-1.png){}\n:::\n:::\n\n\n`15.6` is the most common screen size, followed by `14.0` and `17.3` inches.\n\n::: {.cell execution_count=38}\n``` {.python .cell-code}\nscreen_size_counts = df_clean.inches_size.value_counts().sort_values(ascending = False)\n\nprint(screen_size_counts.head(6).sum()/screen_size_counts.sum())\n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0.9621273166800967\n```\n:::\n:::\n\n\nOnly 4 sizes make up `96.21%` of the laptops in the dataset, which means we can drop the other sizes.\n\n::: {.cell execution_count=39}\n``` {.python .cell-code}\ndf_clean = df_clean[df_clean.inches_size.isin([13.3, 14.0, 15.6, 17.3, 11.6, 12.5])]\n\ndf_clean.inches_size.unique()\n```\n\n::: {.cell-output .cell-output-display execution_count=99}\n```\narray([13.3, 15.6, 14. , 17.3, 12.5, 11.6])\n```\n:::\n:::\n\n\nLet's look at correlation once again.\n\n::: {.cell execution_count=40}\n``` {.python .cell-code}\nsns.heatmap(df_clean.select_dtypes(include = ['int64', 'float64']).corr(),\n            annot = True, cmap = 'coolwarm')\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](laptop_price_prediction_files/figure-docx/cell-41-output-1.png){}\n:::\n:::\n\n\n## Model Building\n\nWe have gone through different parameters of the data now it's time to put that to building a model.\n\nI am going to build 2 models\n1. Random Forest Regressor\n2. Linear Regression Model\n\nand compare them to find the best model.\n\n### Importing Libraries\n\nImporting libraries for model building and evaluation with `sklearn`.\n\n::: {.cell execution_count=41}\n``` {.python .cell-code}\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import LabelEncoder\nfrom sklearn.ensemble import RandomForestRegressor\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.metrics import mean_squared_error, r2_score\n```\n:::\n\n\n### Data Preparation\n\n`RandomForestRegressor` can deal with Null values, so we don't need to handle them for this model, but we need to handle them for `LinearRegression` model.\n\n\nLet's create a copy of the dataset and drop the `price` column.\n\nThen we need to label encode the `cpu_ghz`, `inches_size`, `ram_gb`, `memory_capacity_1`, `memory_capacity_2`, `resolution` columns as they are ordinal data.\n\n::: {.cell execution_count=42}\n``` {.python .cell-code}\ndf_model = df_clean.copy().drop(columns=['price'])\n\nordinal_cols = ['cpu_ghz', 'inches_size', 'ram_gb', 'memory_capacity_1', 'memory_capacity_2', 'resolution', 'weight_kg']\n\nfor col in ordinal_cols:\n    le = LabelEncoder()\n    df_model[col] = le.fit_transform(df_model[col])\n\ndf_model.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=102}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>company</th>\n      <th>typename</th>\n      <th>opsys</th>\n      <th>cpu_brand</th>\n      <th>cpu_name</th>\n      <th>cpu_ghz</th>\n      <th>resolution</th>\n      <th>touchscreen</th>\n      <th>display_type</th>\n      <th>gpu_brand</th>\n      <th>gpu_name</th>\n      <th>memory_capacity_1</th>\n      <th>memory_type_1</th>\n      <th>memory_capacity_2</th>\n      <th>memory_type_2</th>\n      <th>ram_gb</th>\n      <th>inches_size</th>\n      <th>weight_kg</th>\n      <th>price_log</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>macOS</td>\n      <td>Intel</td>\n      <td>Core i5</td>\n      <td>13</td>\n      <td>6</td>\n      <td>0</td>\n      <td>IPS Panel Retina Display</td>\n      <td>Intel</td>\n      <td>Iris Plus Graphics 640</td>\n      <td>4</td>\n      <td>SSD</td>\n      <td>5</td>\n      <td>NaN</td>\n      <td>4</td>\n      <td>2</td>\n      <td>35</td>\n      <td>11.175769</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>macOS</td>\n      <td>Intel</td>\n      <td>Core i5</td>\n      <td>7</td>\n      <td>1</td>\n      <td>0</td>\n      <td></td>\n      <td>Intel</td>\n      <td>HD Graphics 6000</td>\n      <td>4</td>\n      <td>Flash Storage</td>\n      <td>5</td>\n      <td>NaN</td>\n      <td>4</td>\n      <td>2</td>\n      <td>32</td>\n      <td>10.776798</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>HP</td>\n      <td>Notebook</td>\n      <td>No OS</td>\n      <td>Intel</td>\n      <td>Core i5 7200U</td>\n      <td>15</td>\n      <td>3</td>\n      <td>0</td>\n      <td></td>\n      <td>Intel</td>\n      <td>HD Graphics 620</td>\n      <td>7</td>\n      <td>SSD</td>\n      <td>5</td>\n      <td>NaN</td>\n      <td>4</td>\n      <td>4</td>\n      <td>69</td>\n      <td>10.329964</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>macOS</td>\n      <td>Intel</td>\n      <td>Core i5</td>\n      <td>21</td>\n      <td>6</td>\n      <td>0</td>\n      <td>IPS Panel Retina Display</td>\n      <td>Intel</td>\n      <td>Iris Plus Graphics 650</td>\n      <td>7</td>\n      <td>SSD</td>\n      <td>5</td>\n      <td>NaN</td>\n      <td>4</td>\n      <td>2</td>\n      <td>35</td>\n      <td>11.473111</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Acer</td>\n      <td>Notebook</td>\n      <td>Windows 10</td>\n      <td>AMD</td>\n      <td>A9-Series 9420</td>\n      <td>20</td>\n      <td>0</td>\n      <td>0</td>\n      <td></td>\n      <td>AMD</td>\n      <td>Radeon R5</td>\n      <td>8</td>\n      <td>HDD</td>\n      <td>5</td>\n      <td>NaN</td>\n      <td>2</td>\n      <td>4</td>\n      <td>90</td>\n      <td>9.967072</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nWe need to one hot encode the `cpu_brand`, `gpu_brand`, `company`, `display_type`, `touchscreen`, `cpu_name`, `gpu_name` columns as they are categorical data.\n\n::: {.cell execution_count=43}\n``` {.python .cell-code}\nnominal_cols = ['cpu_brand', 'gpu_brand', 'company', 'display_type', 'touchscreen', 'cpu_name', 'gpu_name', 'typename', 'opsys', 'memory_type_1', 'memory_type_2']\n\ndf_model = pd.get_dummies(df_model, columns=nominal_cols, drop_first=True)\n\nprint(df_model.shape)\ndf_model.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(1194, 225)\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=103}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>cpu_ghz</th>\n      <th>resolution</th>\n      <th>memory_capacity_1</th>\n      <th>memory_capacity_2</th>\n      <th>ram_gb</th>\n      <th>inches_size</th>\n      <th>weight_kg</th>\n      <th>price_log</th>\n      <th>cpu_brand_Intel</th>\n      <th>gpu_brand_Intel</th>\n      <th>...</th>\n      <th>opsys_Windows 10</th>\n      <th>opsys_Windows 10 S</th>\n      <th>opsys_Windows 7</th>\n      <th>opsys_macOS</th>\n      <th>memory_type_1_Flash Storage</th>\n      <th>memory_type_1_HDD</th>\n      <th>memory_type_1_Hybrid</th>\n      <th>memory_type_1_SSD</th>\n      <th>memory_type_2_Hybrid</th>\n      <th>memory_type_2_SSD</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>13</td>\n      <td>6</td>\n      <td>4</td>\n      <td>5</td>\n      <td>4</td>\n      <td>2</td>\n      <td>35</td>\n      <td>11.175769</td>\n      <td>True</td>\n      <td>True</td>\n      <td>...</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>7</td>\n      <td>1</td>\n      <td>4</td>\n      <td>5</td>\n      <td>4</td>\n      <td>2</td>\n      <td>32</td>\n      <td>10.776798</td>\n      <td>True</td>\n      <td>True</td>\n      <td>...</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>15</td>\n      <td>3</td>\n      <td>7</td>\n      <td>5</td>\n      <td>4</td>\n      <td>4</td>\n      <td>69</td>\n      <td>10.329964</td>\n      <td>True</td>\n      <td>True</td>\n      <td>...</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>21</td>\n      <td>6</td>\n      <td>7</td>\n      <td>5</td>\n      <td>4</td>\n      <td>2</td>\n      <td>35</td>\n      <td>11.473111</td>\n      <td>True</td>\n      <td>True</td>\n      <td>...</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>20</td>\n      <td>0</td>\n      <td>8</td>\n      <td>5</td>\n      <td>2</td>\n      <td>4</td>\n      <td>90</td>\n      <td>9.967072</td>\n      <td>False</td>\n      <td>False</td>\n      <td>...</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n  </tbody>\n</table>\n<p>5 rows × 225 columns</p>\n</div>\n```\n:::\n:::\n\n\n### Random Forest Regressor\n\n#### Data Preparation\n\nLet's split the data into training and testing sets.\n\n::: {.cell execution_count=44}\n``` {.python .cell-code}\nx = df_model.drop(columns = ['price_log'])\ny = df_model['price_log']\n\nx_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)\n```\n:::\n\n\n#### Model Training & Evaluation\n\nTraining the model with `RandomForestRegressor` and evaluating it with `mean_squared_error` and `r2_score`.\n\n::: {.cell execution_count=45}\n``` {.python .cell-code}\nrf_model = RandomForestRegressor(n_estimators= 100, max_depth = 200, max_features = 20)\nrf_model.fit(x_train, y_train)\n```\n\n::: {.cell-output .cell-output-display execution_count=105}\n```{=html}\n<style>#sk-container-id-4 {\n  /* Definition of color scheme common for light and dark mode */\n  --sklearn-color-text: #000;\n  --sklearn-color-text-muted: #666;\n  --sklearn-color-line: gray;\n  /* Definition of color scheme for unfitted estimators */\n  --sklearn-color-unfitted-level-0: #fff5e6;\n  --sklearn-color-unfitted-level-1: #f6e4d2;\n  --sklearn-color-unfitted-level-2: #ffe0b3;\n  --sklearn-color-unfitted-level-3: chocolate;\n  /* Definition of color scheme for fitted estimators */\n  --sklearn-color-fitted-level-0: #f0f8ff;\n  --sklearn-color-fitted-level-1: #d4ebff;\n  --sklearn-color-fitted-level-2: #b3dbfd;\n  --sklearn-color-fitted-level-3: cornflowerblue;\n\n  /* Specific color for light theme */\n  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n  --sklearn-color-icon: #696969;\n\n  @media (prefers-color-scheme: dark) {\n    /* Redefinition of color scheme for dark theme */\n    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n    --sklearn-color-icon: #878787;\n  }\n}\n\n#sk-container-id-4 {\n  color: var(--sklearn-color-text);\n}\n\n#sk-container-id-4 pre {\n  padding: 0;\n}\n\n#sk-container-id-4 input.sk-hidden--visually {\n  border: 0;\n  clip: rect(1px 1px 1px 1px);\n  clip: rect(1px, 1px, 1px, 1px);\n  height: 1px;\n  margin: -1px;\n  overflow: hidden;\n  padding: 0;\n  position: absolute;\n  width: 1px;\n}\n\n#sk-container-id-4 div.sk-dashed-wrapped {\n  border: 1px dashed var(--sklearn-color-line);\n  margin: 0 0.4em 0.5em 0.4em;\n  box-sizing: border-box;\n  padding-bottom: 0.4em;\n  background-color: var(--sklearn-color-background);\n}\n\n#sk-container-id-4 div.sk-container {\n  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n     but bootstrap.min.css set `[hidden] { display: none !important; }`\n     so we also need the `!important` here to be able to override the\n     default hidden behavior on the sphinx rendered scikit-learn.org.\n     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n  display: inline-block !important;\n  position: relative;\n}\n\n#sk-container-id-4 div.sk-text-repr-fallback {\n  display: none;\n}\n\ndiv.sk-parallel-item,\ndiv.sk-serial,\ndiv.sk-item {\n  /* draw centered vertical line to link estimators */\n  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n  background-size: 2px 100%;\n  background-repeat: no-repeat;\n  background-position: center center;\n}\n\n/* Parallel-specific style estimator block */\n\n#sk-container-id-4 div.sk-parallel-item::after {\n  content: \"\";\n  width: 100%;\n  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n  flex-grow: 1;\n}\n\n#sk-container-id-4 div.sk-parallel {\n  display: flex;\n  align-items: stretch;\n  justify-content: center;\n  background-color: var(--sklearn-color-background);\n  position: relative;\n}\n\n#sk-container-id-4 div.sk-parallel-item {\n  display: flex;\n  flex-direction: column;\n}\n\n#sk-container-id-4 div.sk-parallel-item:first-child::after {\n  align-self: flex-end;\n  width: 50%;\n}\n\n#sk-container-id-4 div.sk-parallel-item:last-child::after {\n  align-self: flex-start;\n  width: 50%;\n}\n\n#sk-container-id-4 div.sk-parallel-item:only-child::after {\n  width: 0;\n}\n\n/* Serial-specific style estimator block */\n\n#sk-container-id-4 div.sk-serial {\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  background-color: var(--sklearn-color-background);\n  padding-right: 1em;\n  padding-left: 1em;\n}\n\n\n/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\nclickable and can be expanded/collapsed.\n- Pipeline and ColumnTransformer use this feature and define the default style\n- Estimators will overwrite some part of the style using the `sk-estimator` class\n*/\n\n/* Pipeline and ColumnTransformer style (default) */\n\n#sk-container-id-4 div.sk-toggleable {\n  /* Default theme specific background. It is overwritten whether we have a\n  specific estimator or a Pipeline/ColumnTransformer */\n  background-color: var(--sklearn-color-background);\n}\n\n/* Toggleable label */\n#sk-container-id-4 label.sk-toggleable__label {\n  cursor: pointer;\n  display: flex;\n  width: 100%;\n  margin-bottom: 0;\n  padding: 0.5em;\n  box-sizing: border-box;\n  text-align: center;\n  align-items: start;\n  justify-content: space-between;\n  gap: 0.5em;\n}\n\n#sk-container-id-4 label.sk-toggleable__label .caption {\n  font-size: 0.6rem;\n  font-weight: lighter;\n  color: var(--sklearn-color-text-muted);\n}\n\n#sk-container-id-4 label.sk-toggleable__label-arrow:before {\n  /* Arrow on the left of the label */\n  content: \"▸\";\n  float: left;\n  margin-right: 0.25em;\n  color: var(--sklearn-color-icon);\n}\n\n#sk-container-id-4 label.sk-toggleable__label-arrow:hover:before {\n  color: var(--sklearn-color-text);\n}\n\n/* Toggleable content - dropdown */\n\n#sk-container-id-4 div.sk-toggleable__content {\n  display: none;\n  text-align: left;\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-4 div.sk-toggleable__content.fitted {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n#sk-container-id-4 div.sk-toggleable__content pre {\n  margin: 0.2em;\n  border-radius: 0.25em;\n  color: var(--sklearn-color-text);\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-4 div.sk-toggleable__content.fitted pre {\n  /* unfitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n#sk-container-id-4 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n  /* Expand drop-down */\n  display: block;\n  width: 100%;\n  overflow: visible;\n}\n\n#sk-container-id-4 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n  content: \"▾\";\n}\n\n/* Pipeline/ColumnTransformer-specific style */\n\n#sk-container-id-4 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-4 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Estimator-specific style */\n\n/* Colorize estimator box */\n#sk-container-id-4 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-4 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n#sk-container-id-4 div.sk-label label.sk-toggleable__label,\n#sk-container-id-4 div.sk-label label {\n  /* The background is the default theme color */\n  color: var(--sklearn-color-text-on-default-background);\n}\n\n/* On hover, darken the color of the background */\n#sk-container-id-4 div.sk-label:hover label.sk-toggleable__label {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n/* Label box, darken color on hover, fitted */\n#sk-container-id-4 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Estimator label */\n\n#sk-container-id-4 div.sk-label label {\n  font-family: monospace;\n  font-weight: bold;\n  display: inline-block;\n  line-height: 1.2em;\n}\n\n#sk-container-id-4 div.sk-label-container {\n  text-align: center;\n}\n\n/* Estimator-specific */\n#sk-container-id-4 div.sk-estimator {\n  font-family: monospace;\n  border: 1px dotted var(--sklearn-color-border-box);\n  border-radius: 0.25em;\n  box-sizing: border-box;\n  margin-bottom: 0.5em;\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-4 div.sk-estimator.fitted {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n/* on hover */\n#sk-container-id-4 div.sk-estimator:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-4 div.sk-estimator.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Specification for estimator info (e.g. \"i\" and \"?\") */\n\n/* Common style for \"i\" and \"?\" */\n\n.sk-estimator-doc-link,\na:link.sk-estimator-doc-link,\na:visited.sk-estimator-doc-link {\n  float: right;\n  font-size: smaller;\n  line-height: 1em;\n  font-family: monospace;\n  background-color: var(--sklearn-color-background);\n  border-radius: 1em;\n  height: 1em;\n  width: 1em;\n  text-decoration: none !important;\n  margin-left: 0.5em;\n  text-align: center;\n  /* unfitted */\n  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n  color: var(--sklearn-color-unfitted-level-1);\n}\n\n.sk-estimator-doc-link.fitted,\na:link.sk-estimator-doc-link.fitted,\na:visited.sk-estimator-doc-link.fitted {\n  /* fitted */\n  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n  color: var(--sklearn-color-fitted-level-1);\n}\n\n/* On hover */\ndiv.sk-estimator:hover .sk-estimator-doc-link:hover,\n.sk-estimator-doc-link:hover,\ndiv.sk-label-container:hover .sk-estimator-doc-link:hover,\n.sk-estimator-doc-link:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\ndiv.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n.sk-estimator-doc-link.fitted:hover,\ndiv.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n.sk-estimator-doc-link.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\n/* Span, style for the box shown on hovering the info icon */\n.sk-estimator-doc-link span {\n  display: none;\n  z-index: 9999;\n  position: relative;\n  font-weight: normal;\n  right: .2ex;\n  padding: .5ex;\n  margin: .5ex;\n  width: min-content;\n  min-width: 20ex;\n  max-width: 50ex;\n  color: var(--sklearn-color-text);\n  box-shadow: 2pt 2pt 4pt #999;\n  /* unfitted */\n  background: var(--sklearn-color-unfitted-level-0);\n  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n}\n\n.sk-estimator-doc-link.fitted span {\n  /* fitted */\n  background: var(--sklearn-color-fitted-level-0);\n  border: var(--sklearn-color-fitted-level-3);\n}\n\n.sk-estimator-doc-link:hover span {\n  display: block;\n}\n\n/* \"?\"-specific style due to the `<a>` HTML tag */\n\n#sk-container-id-4 a.estimator_doc_link {\n  float: right;\n  font-size: 1rem;\n  line-height: 1em;\n  font-family: monospace;\n  background-color: var(--sklearn-color-background);\n  border-radius: 1rem;\n  height: 1rem;\n  width: 1rem;\n  text-decoration: none;\n  /* unfitted */\n  color: var(--sklearn-color-unfitted-level-1);\n  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n}\n\n#sk-container-id-4 a.estimator_doc_link.fitted {\n  /* fitted */\n  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n  color: var(--sklearn-color-fitted-level-1);\n}\n\n/* On hover */\n#sk-container-id-4 a.estimator_doc_link:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\n#sk-container-id-4 a.estimator_doc_link.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-3);\n}\n\n.estimator-table summary {\n    padding: .5rem;\n    font-family: monospace;\n    cursor: pointer;\n}\n\n.estimator-table details[open] {\n    padding-left: 0.1rem;\n    padding-right: 0.1rem;\n    padding-bottom: 0.3rem;\n}\n\n.estimator-table .parameters-table {\n    margin-left: auto !important;\n    margin-right: auto !important;\n}\n\n.estimator-table .parameters-table tr:nth-child(odd) {\n    background-color: #fff;\n}\n\n.estimator-table .parameters-table tr:nth-child(even) {\n    background-color: #f6f6f6;\n}\n\n.estimator-table .parameters-table tr:hover {\n    background-color: #e0e0e0;\n}\n\n.estimator-table table td {\n    border: 1px solid rgba(106, 105, 104, 0.232);\n}\n\n.user-set td {\n    color:rgb(255, 94, 0);\n    text-align: left;\n}\n\n.user-set td.value pre {\n    color:rgb(255, 94, 0) !important;\n    background-color: transparent !important;\n}\n\n.default td {\n    color: black;\n    text-align: left;\n}\n\n.user-set td i,\n.default td i {\n    color: black;\n}\n\n.copy-paste-icon {\n    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);\n    background-repeat: no-repeat;\n    background-size: 14px 14px;\n    background-position: 0;\n    display: inline-block;\n    width: 14px;\n    height: 14px;\n    cursor: pointer;\n}\n</style><body><div id=\"sk-container-id-4\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>RandomForestRegressor(max_depth=200, max_features=20)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-4\" type=\"checkbox\" checked><label for=\"sk-estimator-id-4\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>RandomForestRegressor</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.7/modules/generated/sklearn.ensemble.RandomForestRegressor.html\">?<span>Documentation for RandomForestRegressor</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\" data-param-prefix=\"\">\n        <div class=\"estimator-table\">\n            <details>\n                <summary>Parameters</summary>\n                <table class=\"parameters-table\">\n                  <tbody>\n                    \n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('n_estimators',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">n_estimators&nbsp;</td>\n            <td class=\"value\">100</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('criterion',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">criterion&nbsp;</td>\n            <td class=\"value\">&#x27;squared_error&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_depth',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_depth&nbsp;</td>\n            <td class=\"value\">200</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('min_samples_split',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">min_samples_split&nbsp;</td>\n            <td class=\"value\">2</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('min_samples_leaf',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">min_samples_leaf&nbsp;</td>\n            <td class=\"value\">1</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('min_weight_fraction_leaf',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">min_weight_fraction_leaf&nbsp;</td>\n            <td class=\"value\">0.0</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_features',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_features&nbsp;</td>\n            <td class=\"value\">20</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_leaf_nodes',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_leaf_nodes&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('min_impurity_decrease',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">min_impurity_decrease&nbsp;</td>\n            <td class=\"value\">0.0</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('bootstrap',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">bootstrap&nbsp;</td>\n            <td class=\"value\">True</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('oob_score',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">oob_score&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('n_jobs',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">n_jobs&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('random_state',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">random_state&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('verbose',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">verbose&nbsp;</td>\n            <td class=\"value\">0</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('warm_start',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">warm_start&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('ccp_alpha',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">ccp_alpha&nbsp;</td>\n            <td class=\"value\">0.0</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_samples',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_samples&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('monotonic_cst',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">monotonic_cst&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n                  </tbody>\n                </table>\n            </details>\n        </div>\n    </div></div></div></div></div><script>function copyToClipboard(text, element) {\n    // Get the parameter prefix from the closest toggleable content\n    const toggleableContent = element.closest('.sk-toggleable__content');\n    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;\n\n    const originalStyle = element.style;\n    const computedStyle = window.getComputedStyle(element);\n    const originalWidth = computedStyle.width;\n    const originalHTML = element.innerHTML.replace('Copied!', '');\n\n    navigator.clipboard.writeText(fullParamName)\n        .then(() => {\n            element.style.width = originalWidth;\n            element.style.color = 'green';\n            element.innerHTML = \"Copied!\";\n\n            setTimeout(() => {\n                element.innerHTML = originalHTML;\n                element.style = originalStyle;\n            }, 2000);\n        })\n        .catch(err => {\n            console.error('Failed to copy:', err);\n            element.style.color = 'red';\n            element.innerHTML = \"Failed!\";\n            setTimeout(() => {\n                element.innerHTML = originalHTML;\n                element.style = originalStyle;\n            }, 2000);\n        });\n    return false;\n}\n\ndocument.querySelectorAll('.fa-regular.fa-copy').forEach(function(element) {\n    const toggleableContent = element.closest('.sk-toggleable__content');\n    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n    const paramName = element.parentElement.nextElementSibling.textContent.trim();\n    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;\n\n    element.setAttribute('title', fullParamName);\n});\n</script></body>\n```\n:::\n:::\n\n\n::: {.cell execution_count=46}\n``` {.python .cell-code}\ny_pred = rf_model.predict(x_test)\n\nmse = mean_squared_error(y_test, y_pred)\nr2 = r2_score(y_test, y_pred)\n\nprint(f'Mean Squared Error: {mse:.2f}')\nprint(f'R2 Score: {r2:.2f}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean Squared Error: 0.05\nR2 Score: 0.88\n```\n:::\n:::\n\n\nThe `R2 Score` is `0.88`, which is good and `Mean Squared Error` is `0.04` which is also good for this model.\n\n### Linear Regression Model\n\n#### Data Preparation\n\n::: {.cell execution_count=47}\n``` {.python .cell-code}\ndf_lr = df_clean.copy().drop(columns=['price'])\n\ndf_lr.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nIndex: 1194 entries, 0 to 1273\nData columns (total 19 columns):\n #   Column             Non-Null Count  Dtype  \n---  ------             --------------  -----  \n 0   company            1194 non-null   object \n 1   typename           1194 non-null   object \n 2   opsys              1194 non-null   object \n 3   cpu_brand          1194 non-null   object \n 4   cpu_name           1194 non-null   object \n 5   cpu_ghz            1194 non-null   float64\n 6   resolution         1194 non-null   object \n 7   touchscreen        1194 non-null   int64  \n 8   display_type       1194 non-null   object \n 9   gpu_brand          1194 non-null   object \n 10  gpu_name           1194 non-null   object \n 11  memory_capacity_1  1193 non-null   float64\n 12  memory_type_1      1194 non-null   object \n 13  memory_capacity_2  201 non-null    float64\n 14  memory_type_2      201 non-null    object \n 15  ram_gb             1194 non-null   int64  \n 16  inches_size        1194 non-null   float64\n 17  weight_kg          1193 non-null   float64\n 18  price_log          1194 non-null   float64\ndtypes: float64(6), int64(2), object(11)\nmemory usage: 186.6+ KB\n```\n:::\n:::\n\n\nWe nedd to deal with the missing values in the dataset for `LinearRegression` model.\n\n::: {.cell execution_count=48}\n``` {.python .cell-code}\ndf_lr.isnull().sum()\n```\n\n::: {.cell-output .cell-output-display execution_count=108}\n```\ncompany                0\ntypename               0\nopsys                  0\ncpu_brand              0\ncpu_name               0\ncpu_ghz                0\nresolution             0\ntouchscreen            0\ndisplay_type           0\ngpu_brand              0\ngpu_name               0\nmemory_capacity_1      1\nmemory_type_1          0\nmemory_capacity_2    993\nmemory_type_2        993\nram_gb                 0\ninches_size            0\nweight_kg              1\nprice_log              0\ndtype: int64\n```\n:::\n:::\n\n\nThere are 1 missing values in `weight_kg` column and 1 missing value in `memory_capacity_1`, let's fill it with the median and mean of the columns.\n\n::: {.cell execution_count=49}\n``` {.python .cell-code}\ndf_lr['weight_kg'] = df_lr['weight_kg'].fillna(df_lr['weight_kg'].median())\ndf_lr['memory_capacity_1'] = df_lr['memory_capacity_1'].fillna(df_lr['memory_capacity_1'].mean())\n```\n:::\n\n\n`memory_capacity_2` and `memory_type_2` are lots of missing values, let's fill them with `0`s respectively.\n\n::: {.cell execution_count=50}\n``` {.python .cell-code}\ndf_lr['memory_capacity_2'] = df_lr['memory_capacity_2'].fillna(0)\ndf_lr['memory_type_2'] = df_lr['memory_type_2'].fillna(0)\n```\n:::\n\n\nNow we have filled the missing values in the dataset for `LinearRegression` model. Let's encode the data for `LinearRegression` model.\n\n::: {.cell execution_count=51}\n``` {.python .cell-code}\nordinal_cols = ['cpu_ghz', 'inches_size', 'ram_gb', 'memory_capacity_1', 'memory_capacity_2', 'resolution', 'weight_kg']\n\nfor col in ordinal_cols:\n    le = LabelEncoder()\n    df_lr[col] = le.fit_transform(df_lr[col])\n\ndf_lr.head(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=111}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>company</th>\n      <th>typename</th>\n      <th>opsys</th>\n      <th>cpu_brand</th>\n      <th>cpu_name</th>\n      <th>cpu_ghz</th>\n      <th>resolution</th>\n      <th>touchscreen</th>\n      <th>display_type</th>\n      <th>gpu_brand</th>\n      <th>gpu_name</th>\n      <th>memory_capacity_1</th>\n      <th>memory_type_1</th>\n      <th>memory_capacity_2</th>\n      <th>memory_type_2</th>\n      <th>ram_gb</th>\n      <th>inches_size</th>\n      <th>weight_kg</th>\n      <th>price_log</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>macOS</td>\n      <td>Intel</td>\n      <td>Core i5</td>\n      <td>13</td>\n      <td>6</td>\n      <td>0</td>\n      <td>IPS Panel Retina Display</td>\n      <td>Intel</td>\n      <td>Iris Plus Graphics 640</td>\n      <td>4</td>\n      <td>SSD</td>\n      <td>0</td>\n      <td>0</td>\n      <td>4</td>\n      <td>2</td>\n      <td>35</td>\n      <td>11.175769</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Apple</td>\n      <td>Ultrabook</td>\n      <td>macOS</td>\n      <td>Intel</td>\n      <td>Core i5</td>\n      <td>7</td>\n      <td>1</td>\n      <td>0</td>\n      <td></td>\n      <td>Intel</td>\n      <td>HD Graphics 6000</td>\n      <td>4</td>\n      <td>Flash Storage</td>\n      <td>0</td>\n      <td>0</td>\n      <td>4</td>\n      <td>2</td>\n      <td>32</td>\n      <td>10.776798</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>HP</td>\n      <td>Notebook</td>\n      <td>No OS</td>\n      <td>Intel</td>\n      <td>Core i5 7200U</td>\n      <td>15</td>\n      <td>3</td>\n      <td>0</td>\n      <td></td>\n      <td>Intel</td>\n      <td>HD Graphics 620</td>\n      <td>7</td>\n      <td>SSD</td>\n      <td>0</td>\n      <td>0</td>\n      <td>4</td>\n      <td>4</td>\n      <td>69</td>\n      <td>10.329964</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nWe need to encode nominal data for `LinearRegression` model.\n\n::: {.cell execution_count=52}\n``` {.python .cell-code}\nnominal_cols = ['cpu_brand', 'gpu_brand', 'company', 'display_type', 'touchscreen', 'cpu_name', 'gpu_name', 'typename', 'opsys', 'memory_type_1', 'memory_type_2']\n\ndf_lr = pd.get_dummies(df_lr, columns=nominal_cols, drop_first=True)\n\ndf_lr.head(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=112}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>cpu_ghz</th>\n      <th>resolution</th>\n      <th>memory_capacity_1</th>\n      <th>memory_capacity_2</th>\n      <th>ram_gb</th>\n      <th>inches_size</th>\n      <th>weight_kg</th>\n      <th>price_log</th>\n      <th>cpu_brand_Intel</th>\n      <th>gpu_brand_Intel</th>\n      <th>...</th>\n      <th>opsys_Windows 10 S</th>\n      <th>opsys_Windows 7</th>\n      <th>opsys_macOS</th>\n      <th>memory_type_1_Flash Storage</th>\n      <th>memory_type_1_HDD</th>\n      <th>memory_type_1_Hybrid</th>\n      <th>memory_type_1_SSD</th>\n      <th>memory_type_2_HDD</th>\n      <th>memory_type_2_Hybrid</th>\n      <th>memory_type_2_SSD</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>13</td>\n      <td>6</td>\n      <td>4</td>\n      <td>0</td>\n      <td>4</td>\n      <td>2</td>\n      <td>35</td>\n      <td>11.175769</td>\n      <td>True</td>\n      <td>True</td>\n      <td>...</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>7</td>\n      <td>1</td>\n      <td>4</td>\n      <td>0</td>\n      <td>4</td>\n      <td>2</td>\n      <td>32</td>\n      <td>10.776798</td>\n      <td>True</td>\n      <td>True</td>\n      <td>...</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>15</td>\n      <td>3</td>\n      <td>7</td>\n      <td>0</td>\n      <td>4</td>\n      <td>4</td>\n      <td>69</td>\n      <td>10.329964</td>\n      <td>True</td>\n      <td>True</td>\n      <td>...</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n  </tbody>\n</table>\n<p>3 rows × 226 columns</p>\n</div>\n```\n:::\n:::\n\n\nLet's split the data into training and testing sets.\n\n::: {.cell execution_count=53}\n``` {.python .cell-code}\nx = df_lr.drop(columns = ['price_log'])\ny = df_lr['price_log']\n\nx_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)\n```\n:::\n\n\n#### Model Training & Evaluation\n\nTraining the model with `LinearRegression` and evaluating it with `mean_squared_error` and `r2_score`.\n\n::: {.cell execution_count=54}\n``` {.python .cell-code}\nlr_model = LinearRegression()\n\nlr_model.fit(x_train, y_train)\n```\n\n::: {.cell-output .cell-output-display execution_count=114}\n```{=html}\n<style>#sk-container-id-5 {\n  /* Definition of color scheme common for light and dark mode */\n  --sklearn-color-text: #000;\n  --sklearn-color-text-muted: #666;\n  --sklearn-color-line: gray;\n  /* Definition of color scheme for unfitted estimators */\n  --sklearn-color-unfitted-level-0: #fff5e6;\n  --sklearn-color-unfitted-level-1: #f6e4d2;\n  --sklearn-color-unfitted-level-2: #ffe0b3;\n  --sklearn-color-unfitted-level-3: chocolate;\n  /* Definition of color scheme for fitted estimators */\n  --sklearn-color-fitted-level-0: #f0f8ff;\n  --sklearn-color-fitted-level-1: #d4ebff;\n  --sklearn-color-fitted-level-2: #b3dbfd;\n  --sklearn-color-fitted-level-3: cornflowerblue;\n\n  /* Specific color for light theme */\n  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n  --sklearn-color-icon: #696969;\n\n  @media (prefers-color-scheme: dark) {\n    /* Redefinition of color scheme for dark theme */\n    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n    --sklearn-color-icon: #878787;\n  }\n}\n\n#sk-container-id-5 {\n  color: var(--sklearn-color-text);\n}\n\n#sk-container-id-5 pre {\n  padding: 0;\n}\n\n#sk-container-id-5 input.sk-hidden--visually {\n  border: 0;\n  clip: rect(1px 1px 1px 1px);\n  clip: rect(1px, 1px, 1px, 1px);\n  height: 1px;\n  margin: -1px;\n  overflow: hidden;\n  padding: 0;\n  position: absolute;\n  width: 1px;\n}\n\n#sk-container-id-5 div.sk-dashed-wrapped {\n  border: 1px dashed var(--sklearn-color-line);\n  margin: 0 0.4em 0.5em 0.4em;\n  box-sizing: border-box;\n  padding-bottom: 0.4em;\n  background-color: var(--sklearn-color-background);\n}\n\n#sk-container-id-5 div.sk-container {\n  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n     but bootstrap.min.css set `[hidden] { display: none !important; }`\n     so we also need the `!important` here to be able to override the\n     default hidden behavior on the sphinx rendered scikit-learn.org.\n     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n  display: inline-block !important;\n  position: relative;\n}\n\n#sk-container-id-5 div.sk-text-repr-fallback {\n  display: none;\n}\n\ndiv.sk-parallel-item,\ndiv.sk-serial,\ndiv.sk-item {\n  /* draw centered vertical line to link estimators */\n  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n  background-size: 2px 100%;\n  background-repeat: no-repeat;\n  background-position: center center;\n}\n\n/* Parallel-specific style estimator block */\n\n#sk-container-id-5 div.sk-parallel-item::after {\n  content: \"\";\n  width: 100%;\n  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n  flex-grow: 1;\n}\n\n#sk-container-id-5 div.sk-parallel {\n  display: flex;\n  align-items: stretch;\n  justify-content: center;\n  background-color: var(--sklearn-color-background);\n  position: relative;\n}\n\n#sk-container-id-5 div.sk-parallel-item {\n  display: flex;\n  flex-direction: column;\n}\n\n#sk-container-id-5 div.sk-parallel-item:first-child::after {\n  align-self: flex-end;\n  width: 50%;\n}\n\n#sk-container-id-5 div.sk-parallel-item:last-child::after {\n  align-self: flex-start;\n  width: 50%;\n}\n\n#sk-container-id-5 div.sk-parallel-item:only-child::after {\n  width: 0;\n}\n\n/* Serial-specific style estimator block */\n\n#sk-container-id-5 div.sk-serial {\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  background-color: var(--sklearn-color-background);\n  padding-right: 1em;\n  padding-left: 1em;\n}\n\n\n/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\nclickable and can be expanded/collapsed.\n- Pipeline and ColumnTransformer use this feature and define the default style\n- Estimators will overwrite some part of the style using the `sk-estimator` class\n*/\n\n/* Pipeline and ColumnTransformer style (default) */\n\n#sk-container-id-5 div.sk-toggleable {\n  /* Default theme specific background. It is overwritten whether we have a\n  specific estimator or a Pipeline/ColumnTransformer */\n  background-color: var(--sklearn-color-background);\n}\n\n/* Toggleable label */\n#sk-container-id-5 label.sk-toggleable__label {\n  cursor: pointer;\n  display: flex;\n  width: 100%;\n  margin-bottom: 0;\n  padding: 0.5em;\n  box-sizing: border-box;\n  text-align: center;\n  align-items: start;\n  justify-content: space-between;\n  gap: 0.5em;\n}\n\n#sk-container-id-5 label.sk-toggleable__label .caption {\n  font-size: 0.6rem;\n  font-weight: lighter;\n  color: var(--sklearn-color-text-muted);\n}\n\n#sk-container-id-5 label.sk-toggleable__label-arrow:before {\n  /* Arrow on the left of the label */\n  content: \"▸\";\n  float: left;\n  margin-right: 0.25em;\n  color: var(--sklearn-color-icon);\n}\n\n#sk-container-id-5 label.sk-toggleable__label-arrow:hover:before {\n  color: var(--sklearn-color-text);\n}\n\n/* Toggleable content - dropdown */\n\n#sk-container-id-5 div.sk-toggleable__content {\n  display: none;\n  text-align: left;\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-5 div.sk-toggleable__content.fitted {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n#sk-container-id-5 div.sk-toggleable__content pre {\n  margin: 0.2em;\n  border-radius: 0.25em;\n  color: var(--sklearn-color-text);\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-5 div.sk-toggleable__content.fitted pre {\n  /* unfitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n#sk-container-id-5 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n  /* Expand drop-down */\n  display: block;\n  width: 100%;\n  overflow: visible;\n}\n\n#sk-container-id-5 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n  content: \"▾\";\n}\n\n/* Pipeline/ColumnTransformer-specific style */\n\n#sk-container-id-5 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-5 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Estimator-specific style */\n\n/* Colorize estimator box */\n#sk-container-id-5 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-5 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n#sk-container-id-5 div.sk-label label.sk-toggleable__label,\n#sk-container-id-5 div.sk-label label {\n  /* The background is the default theme color */\n  color: var(--sklearn-color-text-on-default-background);\n}\n\n/* On hover, darken the color of the background */\n#sk-container-id-5 div.sk-label:hover label.sk-toggleable__label {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n/* Label box, darken color on hover, fitted */\n#sk-container-id-5 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Estimator label */\n\n#sk-container-id-5 div.sk-label label {\n  font-family: monospace;\n  font-weight: bold;\n  display: inline-block;\n  line-height: 1.2em;\n}\n\n#sk-container-id-5 div.sk-label-container {\n  text-align: center;\n}\n\n/* Estimator-specific */\n#sk-container-id-5 div.sk-estimator {\n  font-family: monospace;\n  border: 1px dotted var(--sklearn-color-border-box);\n  border-radius: 0.25em;\n  box-sizing: border-box;\n  margin-bottom: 0.5em;\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-5 div.sk-estimator.fitted {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n/* on hover */\n#sk-container-id-5 div.sk-estimator:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-5 div.sk-estimator.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Specification for estimator info (e.g. \"i\" and \"?\") */\n\n/* Common style for \"i\" and \"?\" */\n\n.sk-estimator-doc-link,\na:link.sk-estimator-doc-link,\na:visited.sk-estimator-doc-link {\n  float: right;\n  font-size: smaller;\n  line-height: 1em;\n  font-family: monospace;\n  background-color: var(--sklearn-color-background);\n  border-radius: 1em;\n  height: 1em;\n  width: 1em;\n  text-decoration: none !important;\n  margin-left: 0.5em;\n  text-align: center;\n  /* unfitted */\n  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n  color: var(--sklearn-color-unfitted-level-1);\n}\n\n.sk-estimator-doc-link.fitted,\na:link.sk-estimator-doc-link.fitted,\na:visited.sk-estimator-doc-link.fitted {\n  /* fitted */\n  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n  color: var(--sklearn-color-fitted-level-1);\n}\n\n/* On hover */\ndiv.sk-estimator:hover .sk-estimator-doc-link:hover,\n.sk-estimator-doc-link:hover,\ndiv.sk-label-container:hover .sk-estimator-doc-link:hover,\n.sk-estimator-doc-link:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\ndiv.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n.sk-estimator-doc-link.fitted:hover,\ndiv.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n.sk-estimator-doc-link.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\n/* Span, style for the box shown on hovering the info icon */\n.sk-estimator-doc-link span {\n  display: none;\n  z-index: 9999;\n  position: relative;\n  font-weight: normal;\n  right: .2ex;\n  padding: .5ex;\n  margin: .5ex;\n  width: min-content;\n  min-width: 20ex;\n  max-width: 50ex;\n  color: var(--sklearn-color-text);\n  box-shadow: 2pt 2pt 4pt #999;\n  /* unfitted */\n  background: var(--sklearn-color-unfitted-level-0);\n  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n}\n\n.sk-estimator-doc-link.fitted span {\n  /* fitted */\n  background: var(--sklearn-color-fitted-level-0);\n  border: var(--sklearn-color-fitted-level-3);\n}\n\n.sk-estimator-doc-link:hover span {\n  display: block;\n}\n\n/* \"?\"-specific style due to the `<a>` HTML tag */\n\n#sk-container-id-5 a.estimator_doc_link {\n  float: right;\n  font-size: 1rem;\n  line-height: 1em;\n  font-family: monospace;\n  background-color: var(--sklearn-color-background);\n  border-radius: 1rem;\n  height: 1rem;\n  width: 1rem;\n  text-decoration: none;\n  /* unfitted */\n  color: var(--sklearn-color-unfitted-level-1);\n  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n}\n\n#sk-container-id-5 a.estimator_doc_link.fitted {\n  /* fitted */\n  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n  color: var(--sklearn-color-fitted-level-1);\n}\n\n/* On hover */\n#sk-container-id-5 a.estimator_doc_link:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\n#sk-container-id-5 a.estimator_doc_link.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-3);\n}\n\n.estimator-table summary {\n    padding: .5rem;\n    font-family: monospace;\n    cursor: pointer;\n}\n\n.estimator-table details[open] {\n    padding-left: 0.1rem;\n    padding-right: 0.1rem;\n    padding-bottom: 0.3rem;\n}\n\n.estimator-table .parameters-table {\n    margin-left: auto !important;\n    margin-right: auto !important;\n}\n\n.estimator-table .parameters-table tr:nth-child(odd) {\n    background-color: #fff;\n}\n\n.estimator-table .parameters-table tr:nth-child(even) {\n    background-color: #f6f6f6;\n}\n\n.estimator-table .parameters-table tr:hover {\n    background-color: #e0e0e0;\n}\n\n.estimator-table table td {\n    border: 1px solid rgba(106, 105, 104, 0.232);\n}\n\n.user-set td {\n    color:rgb(255, 94, 0);\n    text-align: left;\n}\n\n.user-set td.value pre {\n    color:rgb(255, 94, 0) !important;\n    background-color: transparent !important;\n}\n\n.default td {\n    color: black;\n    text-align: left;\n}\n\n.user-set td i,\n.default td i {\n    color: black;\n}\n\n.copy-paste-icon {\n    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);\n    background-repeat: no-repeat;\n    background-size: 14px 14px;\n    background-position: 0;\n    display: inline-block;\n    width: 14px;\n    height: 14px;\n    cursor: pointer;\n}\n</style><body><div id=\"sk-container-id-5\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>LinearRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-5\" type=\"checkbox\" checked><label for=\"sk-estimator-id-5\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>LinearRegression</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.7/modules/generated/sklearn.linear_model.LinearRegression.html\">?<span>Documentation for LinearRegression</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\" data-param-prefix=\"\">\n        <div class=\"estimator-table\">\n            <details>\n                <summary>Parameters</summary>\n                <table class=\"parameters-table\">\n                  <tbody>\n                    \n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('fit_intercept',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">fit_intercept&nbsp;</td>\n            <td class=\"value\">True</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('copy_X',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">copy_X&nbsp;</td>\n            <td class=\"value\">True</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('tol',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">tol&nbsp;</td>\n            <td class=\"value\">1e-06</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('n_jobs',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">n_jobs&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('positive',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">positive&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n                  </tbody>\n                </table>\n            </details>\n        </div>\n    </div></div></div></div></div><script>function copyToClipboard(text, element) {\n    // Get the parameter prefix from the closest toggleable content\n    const toggleableContent = element.closest('.sk-toggleable__content');\n    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;\n\n    const originalStyle = element.style;\n    const computedStyle = window.getComputedStyle(element);\n    const originalWidth = computedStyle.width;\n    const originalHTML = element.innerHTML.replace('Copied!', '');\n\n    navigator.clipboard.writeText(fullParamName)\n        .then(() => {\n            element.style.width = originalWidth;\n            element.style.color = 'green';\n            element.innerHTML = \"Copied!\";\n\n            setTimeout(() => {\n                element.innerHTML = originalHTML;\n                element.style = originalStyle;\n            }, 2000);\n        })\n        .catch(err => {\n            console.error('Failed to copy:', err);\n            element.style.color = 'red';\n            element.innerHTML = \"Failed!\";\n            setTimeout(() => {\n                element.innerHTML = originalHTML;\n                element.style = originalStyle;\n            }, 2000);\n        });\n    return false;\n}\n\ndocument.querySelectorAll('.fa-regular.fa-copy').forEach(function(element) {\n    const toggleableContent = element.closest('.sk-toggleable__content');\n    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n    const paramName = element.parentElement.nextElementSibling.textContent.trim();\n    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;\n\n    element.setAttribute('title', fullParamName);\n});\n</script></body>\n```\n:::\n:::\n\n\nModel evaluation\n\n::: {.cell execution_count=55}\n``` {.python .cell-code}\ny_pred = lr_model.predict(x_test)\n\nmse = mean_squared_error(y_test, y_pred)\nr2 = r2_score(y_test, y_pred)\n\n\nprint(f'Mean Squared Error: {mse:.2f}')\nprint(f'R2 Score: {r2:.2f}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean Squared Error: 0.06\nR2 Score: 0.85\n```\n:::\n:::\n\n\nThe `R2 Score` is `0.85`, which is good and `Mean Squared Error` is `0.06` which is also good for this model.\n\n## Model Featue Importance\n\n#### Random Forest Regressor Features\n\nWe know that `RandomForestRegressor` is a tree based model, so we can use `feature_importances_` to get the importance of each feature.\n\n::: {.cell execution_count=56}\n``` {.python .cell-code}\nfeature_importances = pd.DataFrame({'feature': df_model.drop(columns=['price_log']).columns, 'importance': rf_model.feature_importances_.round(4)})\nfeature_importances = feature_importances.sort_values('importance', ascending=False)\nfeature_importances.head(10)\n```\n\n::: {.cell-output .cell-output-display execution_count=116}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>feature</th>\n      <th>importance</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>4</th>\n      <td>ram_gb</td>\n      <td>0.1412</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>cpu_ghz</td>\n      <td>0.0924</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>resolution</td>\n      <td>0.0789</td>\n    </tr>\n    <tr>\n      <th>221</th>\n      <td>memory_type_1_SSD</td>\n      <td>0.0707</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>memory_capacity_1</td>\n      <td>0.0695</td>\n    </tr>\n    <tr>\n      <th>208</th>\n      <td>typename_Notebook</td>\n      <td>0.0686</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>weight_kg</td>\n      <td>0.0632</td>\n    </tr>\n    <tr>\n      <th>219</th>\n      <td>memory_type_1_HDD</td>\n      <td>0.0446</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>inches_size</td>\n      <td>0.0288</td>\n    </tr>\n    <tr>\n      <th>209</th>\n      <td>typename_Ultrabook</td>\n      <td>0.0186</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n#### Linear Regression Features\n\nWe know that `LinearRegression` is a linear model, so we can use `coef_` to get the importance of each feature.\n\n::: {.cell execution_count=57}\n``` {.python .cell-code}\nfeature_importances = pd.DataFrame({'feature': df_lr.drop(columns=['price_log']).columns, 'importance': lr_model.coef_.round(4)})\nfeature_importances = feature_importances.sort_values('importance', ascending=False)\nfeature_importances.head(10)\n```\n\n::: {.cell-output .cell-output-display execution_count=117}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>feature</th>\n      <th>importance</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>170</th>\n      <td>gpu_name_Quadro M3000M</td>\n      <td>0.7551</td>\n    </tr>\n    <tr>\n      <th>174</th>\n      <td>gpu_name_Quadro M620M</td>\n      <td>0.6704</td>\n    </tr>\n    <tr>\n      <th>85</th>\n      <td>cpu_name_Core i7 7820HK</td>\n      <td>0.5735</td>\n    </tr>\n    <tr>\n      <th>110</th>\n      <td>gpu_name_FirePro W6150M</td>\n      <td>0.5047</td>\n    </tr>\n    <tr>\n      <th>79</th>\n      <td>cpu_name_Core i7 6820HQ</td>\n      <td>0.5022</td>\n    </tr>\n    <tr>\n      <th>107</th>\n      <td>cpu_name_Xeon E3-1535M v5</td>\n      <td>0.4997</td>\n    </tr>\n    <tr>\n      <th>167</th>\n      <td>gpu_name_Quadro M2000M</td>\n      <td>0.4997</td>\n    </tr>\n    <tr>\n      <th>142</th>\n      <td>gpu_name_GeForce GTX1080</td>\n      <td>0.4850</td>\n    </tr>\n    <tr>\n      <th>53</th>\n      <td>cpu_name_Core M 6Y54</td>\n      <td>0.4813</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>company_LG</td>\n      <td>0.4473</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Hyperparameter Tuning\n\nI will choose `RandomForestRegressor` for hyperparameter tuning as it has features which are easily explainable and a tree based model can be easily tunable.\n\n`GridSearchCV` is used to tune the hyperparameters of the model. `n_estimators` is the number of trees in the forest, `max_depth` is the maximum depth of the tree, `max_features` is the number of features to consider when looking for the best split.\n\n::: {.cell execution_count=58}\n``` {.python .cell-code}\nfrom sklearn.model_selection import GridSearchCV\n\nparam_grid = {\n    'n_estimators': [50, 100],\n    'max_depth': [10, 20],\n    'max_features': [5, 10, 15]\n}\n\ngrid_search = GridSearchCV(estimator = rf_model, param_grid = param_grid, cv = 5, scoring = 'neg_mean_squared_error', verbose = 2)\ngrid_search.fit(x_train, y_train)\n\nprint(grid_search.best_params_)\nprint(grid_search.best_score_)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFitting 5 folds for each of 12 candidates, totalling 60 fits\n[CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.0s\n[CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.0s\n[CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.0s\n[CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.1s\n[CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.1s\n[CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.1s\n[CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.2s\n[CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.1s\n[CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.1s\n[CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.1s\n[CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.0s\n[CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.0s\n[CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.0s\n[CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.0s\n[CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.0s\n[CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.1s\n[CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.1s\n[CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.1s\n[CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.1s\n[CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.1s\n[CV] END .....max_depth=10, max_features=15, n_estimators=50; total time=   0.0s\n[CV] END .....max_depth=10, max_features=15, n_estimators=50; total time=   0.0s\n[CV] END .....max_depth=10, max_features=15, n_estimators=50; total time=   0.0s\n[CV] END .....max_depth=10, max_features=15, n_estimators=50; total time=   0.0s\n[CV] END .....max_depth=10, max_features=15, n_estimators=50; total time=   0.0s\n[CV] END ....max_depth=10, max_features=15, n_estimators=100; total time=   0.1s\n[CV] END ....max_depth=10, max_features=15, n_estimators=100; total time=   0.1s\n[CV] END ....max_depth=10, max_features=15, n_estimators=100; total time=   0.1s\n[CV] END ....max_depth=10, max_features=15, n_estimators=100; total time=   0.1s\n[CV] END ....max_depth=10, max_features=15, n_estimators=100; total time=   0.1s\n[CV] END ......max_depth=20, max_features=5, n_estimators=50; total time=   0.1s\n[CV] END ......max_depth=20, max_features=5, n_estimators=50; total time=   0.0s\n[CV] END ......max_depth=20, max_features=5, n_estimators=50; total time=   0.1s\n[CV] END ......max_depth=20, max_features=5, n_estimators=50; total time=   0.0s\n[CV] END ......max_depth=20, max_features=5, n_estimators=50; total time=   0.1s\n[CV] END .....max_depth=20, max_features=5, n_estimators=100; total time=   0.2s\n[CV] END .....max_depth=20, max_features=5, n_estimators=100; total time=   0.2s\n[CV] END .....max_depth=20, max_features=5, n_estimators=100; total time=   0.2s\n[CV] END .....max_depth=20, max_features=5, n_estimators=100; total time=   0.3s\n[CV] END .....max_depth=20, max_features=5, n_estimators=100; total time=   0.3s\n[CV] END .....max_depth=20, max_features=10, n_estimators=50; total time=   0.1s\n[CV] END .....max_depth=20, max_features=10, n_estimators=50; total time=   0.1s\n[CV] END .....max_depth=20, max_features=10, n_estimators=50; total time=   0.1s\n[CV] END .....max_depth=20, max_features=10, n_estimators=50; total time=   0.1s\n[CV] END .....max_depth=20, max_features=10, n_estimators=50; total time=   0.1s\n[CV] END ....max_depth=20, max_features=10, n_estimators=100; total time=   0.2s\n[CV] END ....max_depth=20, max_features=10, n_estimators=100; total time=   0.2s\n[CV] END ....max_depth=20, max_features=10, n_estimators=100; total time=   0.2s\n[CV] END ....max_depth=20, max_features=10, n_estimators=100; total time=   0.3s\n[CV] END ....max_depth=20, max_features=10, n_estimators=100; total time=   0.2s\n[CV] END .....max_depth=20, max_features=15, n_estimators=50; total time=   0.1s\n[CV] END .....max_depth=20, max_features=15, n_estimators=50; total time=   0.1s\n[CV] END .....max_depth=20, max_features=15, n_estimators=50; total time=   0.1s\n[CV] END .....max_depth=20, max_features=15, n_estimators=50; total time=   0.1s\n[CV] END .....max_depth=20, max_features=15, n_estimators=50; total time=   0.1s\n[CV] END ....max_depth=20, max_features=15, n_estimators=100; total time=   0.2s\n[CV] END ....max_depth=20, max_features=15, n_estimators=100; total time=   0.2s\n[CV] END ....max_depth=20, max_features=15, n_estimators=100; total time=   0.3s\n[CV] END ....max_depth=20, max_features=15, n_estimators=100; total time=   0.3s\n[CV] END ....max_depth=20, max_features=15, n_estimators=100; total time=   0.3s\n{'max_depth': 20, 'max_features': 15, 'n_estimators': 100}\n-0.044818849215607484\n```\n:::\n:::\n\n\n`grid_search.best_params_` gives the best parameters for the model depending on the scoring metric which is `neg_mean_squared_error` in this case.\n\nThe best parameters are `n_estimators = 100`, `max_depth = 30`, `max_features = 15` and the best score is `-0.042`.\n\n::: {.cell execution_count=59}\n``` {.python .cell-code}\nrf_model = RandomForestRegressor(n_estimators = 100, max_depth = 30, max_features = 15)\nrf_model.fit(x_train, y_train)\n```\n\n::: {.cell-output .cell-output-display execution_count=119}\n```{=html}\n<style>#sk-container-id-6 {\n  /* Definition of color scheme common for light and dark mode */\n  --sklearn-color-text: #000;\n  --sklearn-color-text-muted: #666;\n  --sklearn-color-line: gray;\n  /* Definition of color scheme for unfitted estimators */\n  --sklearn-color-unfitted-level-0: #fff5e6;\n  --sklearn-color-unfitted-level-1: #f6e4d2;\n  --sklearn-color-unfitted-level-2: #ffe0b3;\n  --sklearn-color-unfitted-level-3: chocolate;\n  /* Definition of color scheme for fitted estimators */\n  --sklearn-color-fitted-level-0: #f0f8ff;\n  --sklearn-color-fitted-level-1: #d4ebff;\n  --sklearn-color-fitted-level-2: #b3dbfd;\n  --sklearn-color-fitted-level-3: cornflowerblue;\n\n  /* Specific color for light theme */\n  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n  --sklearn-color-icon: #696969;\n\n  @media (prefers-color-scheme: dark) {\n    /* Redefinition of color scheme for dark theme */\n    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n    --sklearn-color-icon: #878787;\n  }\n}\n\n#sk-container-id-6 {\n  color: var(--sklearn-color-text);\n}\n\n#sk-container-id-6 pre {\n  padding: 0;\n}\n\n#sk-container-id-6 input.sk-hidden--visually {\n  border: 0;\n  clip: rect(1px 1px 1px 1px);\n  clip: rect(1px, 1px, 1px, 1px);\n  height: 1px;\n  margin: -1px;\n  overflow: hidden;\n  padding: 0;\n  position: absolute;\n  width: 1px;\n}\n\n#sk-container-id-6 div.sk-dashed-wrapped {\n  border: 1px dashed var(--sklearn-color-line);\n  margin: 0 0.4em 0.5em 0.4em;\n  box-sizing: border-box;\n  padding-bottom: 0.4em;\n  background-color: var(--sklearn-color-background);\n}\n\n#sk-container-id-6 div.sk-container {\n  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n     but bootstrap.min.css set `[hidden] { display: none !important; }`\n     so we also need the `!important` here to be able to override the\n     default hidden behavior on the sphinx rendered scikit-learn.org.\n     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n  display: inline-block !important;\n  position: relative;\n}\n\n#sk-container-id-6 div.sk-text-repr-fallback {\n  display: none;\n}\n\ndiv.sk-parallel-item,\ndiv.sk-serial,\ndiv.sk-item {\n  /* draw centered vertical line to link estimators */\n  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n  background-size: 2px 100%;\n  background-repeat: no-repeat;\n  background-position: center center;\n}\n\n/* Parallel-specific style estimator block */\n\n#sk-container-id-6 div.sk-parallel-item::after {\n  content: \"\";\n  width: 100%;\n  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n  flex-grow: 1;\n}\n\n#sk-container-id-6 div.sk-parallel {\n  display: flex;\n  align-items: stretch;\n  justify-content: center;\n  background-color: var(--sklearn-color-background);\n  position: relative;\n}\n\n#sk-container-id-6 div.sk-parallel-item {\n  display: flex;\n  flex-direction: column;\n}\n\n#sk-container-id-6 div.sk-parallel-item:first-child::after {\n  align-self: flex-end;\n  width: 50%;\n}\n\n#sk-container-id-6 div.sk-parallel-item:last-child::after {\n  align-self: flex-start;\n  width: 50%;\n}\n\n#sk-container-id-6 div.sk-parallel-item:only-child::after {\n  width: 0;\n}\n\n/* Serial-specific style estimator block */\n\n#sk-container-id-6 div.sk-serial {\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  background-color: var(--sklearn-color-background);\n  padding-right: 1em;\n  padding-left: 1em;\n}\n\n\n/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\nclickable and can be expanded/collapsed.\n- Pipeline and ColumnTransformer use this feature and define the default style\n- Estimators will overwrite some part of the style using the `sk-estimator` class\n*/\n\n/* Pipeline and ColumnTransformer style (default) */\n\n#sk-container-id-6 div.sk-toggleable {\n  /* Default theme specific background. It is overwritten whether we have a\n  specific estimator or a Pipeline/ColumnTransformer */\n  background-color: var(--sklearn-color-background);\n}\n\n/* Toggleable label */\n#sk-container-id-6 label.sk-toggleable__label {\n  cursor: pointer;\n  display: flex;\n  width: 100%;\n  margin-bottom: 0;\n  padding: 0.5em;\n  box-sizing: border-box;\n  text-align: center;\n  align-items: start;\n  justify-content: space-between;\n  gap: 0.5em;\n}\n\n#sk-container-id-6 label.sk-toggleable__label .caption {\n  font-size: 0.6rem;\n  font-weight: lighter;\n  color: var(--sklearn-color-text-muted);\n}\n\n#sk-container-id-6 label.sk-toggleable__label-arrow:before {\n  /* Arrow on the left of the label */\n  content: \"▸\";\n  float: left;\n  margin-right: 0.25em;\n  color: var(--sklearn-color-icon);\n}\n\n#sk-container-id-6 label.sk-toggleable__label-arrow:hover:before {\n  color: var(--sklearn-color-text);\n}\n\n/* Toggleable content - dropdown */\n\n#sk-container-id-6 div.sk-toggleable__content {\n  display: none;\n  text-align: left;\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-6 div.sk-toggleable__content.fitted {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n#sk-container-id-6 div.sk-toggleable__content pre {\n  margin: 0.2em;\n  border-radius: 0.25em;\n  color: var(--sklearn-color-text);\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-6 div.sk-toggleable__content.fitted pre {\n  /* unfitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n#sk-container-id-6 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n  /* Expand drop-down */\n  display: block;\n  width: 100%;\n  overflow: visible;\n}\n\n#sk-container-id-6 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n  content: \"▾\";\n}\n\n/* Pipeline/ColumnTransformer-specific style */\n\n#sk-container-id-6 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-6 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Estimator-specific style */\n\n/* Colorize estimator box */\n#sk-container-id-6 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-6 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n#sk-container-id-6 div.sk-label label.sk-toggleable__label,\n#sk-container-id-6 div.sk-label label {\n  /* The background is the default theme color */\n  color: var(--sklearn-color-text-on-default-background);\n}\n\n/* On hover, darken the color of the background */\n#sk-container-id-6 div.sk-label:hover label.sk-toggleable__label {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n/* Label box, darken color on hover, fitted */\n#sk-container-id-6 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Estimator label */\n\n#sk-container-id-6 div.sk-label label {\n  font-family: monospace;\n  font-weight: bold;\n  display: inline-block;\n  line-height: 1.2em;\n}\n\n#sk-container-id-6 div.sk-label-container {\n  text-align: center;\n}\n\n/* Estimator-specific */\n#sk-container-id-6 div.sk-estimator {\n  font-family: monospace;\n  border: 1px dotted var(--sklearn-color-border-box);\n  border-radius: 0.25em;\n  box-sizing: border-box;\n  margin-bottom: 0.5em;\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-6 div.sk-estimator.fitted {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n/* on hover */\n#sk-container-id-6 div.sk-estimator:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-6 div.sk-estimator.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Specification for estimator info (e.g. \"i\" and \"?\") */\n\n/* Common style for \"i\" and \"?\" */\n\n.sk-estimator-doc-link,\na:link.sk-estimator-doc-link,\na:visited.sk-estimator-doc-link {\n  float: right;\n  font-size: smaller;\n  line-height: 1em;\n  font-family: monospace;\n  background-color: var(--sklearn-color-background);\n  border-radius: 1em;\n  height: 1em;\n  width: 1em;\n  text-decoration: none !important;\n  margin-left: 0.5em;\n  text-align: center;\n  /* unfitted */\n  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n  color: var(--sklearn-color-unfitted-level-1);\n}\n\n.sk-estimator-doc-link.fitted,\na:link.sk-estimator-doc-link.fitted,\na:visited.sk-estimator-doc-link.fitted {\n  /* fitted */\n  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n  color: var(--sklearn-color-fitted-level-1);\n}\n\n/* On hover */\ndiv.sk-estimator:hover .sk-estimator-doc-link:hover,\n.sk-estimator-doc-link:hover,\ndiv.sk-label-container:hover .sk-estimator-doc-link:hover,\n.sk-estimator-doc-link:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\ndiv.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n.sk-estimator-doc-link.fitted:hover,\ndiv.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n.sk-estimator-doc-link.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\n/* Span, style for the box shown on hovering the info icon */\n.sk-estimator-doc-link span {\n  display: none;\n  z-index: 9999;\n  position: relative;\n  font-weight: normal;\n  right: .2ex;\n  padding: .5ex;\n  margin: .5ex;\n  width: min-content;\n  min-width: 20ex;\n  max-width: 50ex;\n  color: var(--sklearn-color-text);\n  box-shadow: 2pt 2pt 4pt #999;\n  /* unfitted */\n  background: var(--sklearn-color-unfitted-level-0);\n  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n}\n\n.sk-estimator-doc-link.fitted span {\n  /* fitted */\n  background: var(--sklearn-color-fitted-level-0);\n  border: var(--sklearn-color-fitted-level-3);\n}\n\n.sk-estimator-doc-link:hover span {\n  display: block;\n}\n\n/* \"?\"-specific style due to the `<a>` HTML tag */\n\n#sk-container-id-6 a.estimator_doc_link {\n  float: right;\n  font-size: 1rem;\n  line-height: 1em;\n  font-family: monospace;\n  background-color: var(--sklearn-color-background);\n  border-radius: 1rem;\n  height: 1rem;\n  width: 1rem;\n  text-decoration: none;\n  /* unfitted */\n  color: var(--sklearn-color-unfitted-level-1);\n  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n}\n\n#sk-container-id-6 a.estimator_doc_link.fitted {\n  /* fitted */\n  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n  color: var(--sklearn-color-fitted-level-1);\n}\n\n/* On hover */\n#sk-container-id-6 a.estimator_doc_link:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\n#sk-container-id-6 a.estimator_doc_link.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-3);\n}\n\n.estimator-table summary {\n    padding: .5rem;\n    font-family: monospace;\n    cursor: pointer;\n}\n\n.estimator-table details[open] {\n    padding-left: 0.1rem;\n    padding-right: 0.1rem;\n    padding-bottom: 0.3rem;\n}\n\n.estimator-table .parameters-table {\n    margin-left: auto !important;\n    margin-right: auto !important;\n}\n\n.estimator-table .parameters-table tr:nth-child(odd) {\n    background-color: #fff;\n}\n\n.estimator-table .parameters-table tr:nth-child(even) {\n    background-color: #f6f6f6;\n}\n\n.estimator-table .parameters-table tr:hover {\n    background-color: #e0e0e0;\n}\n\n.estimator-table table td {\n    border: 1px solid rgba(106, 105, 104, 0.232);\n}\n\n.user-set td {\n    color:rgb(255, 94, 0);\n    text-align: left;\n}\n\n.user-set td.value pre {\n    color:rgb(255, 94, 0) !important;\n    background-color: transparent !important;\n}\n\n.default td {\n    color: black;\n    text-align: left;\n}\n\n.user-set td i,\n.default td i {\n    color: black;\n}\n\n.copy-paste-icon {\n    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);\n    background-repeat: no-repeat;\n    background-size: 14px 14px;\n    background-position: 0;\n    display: inline-block;\n    width: 14px;\n    height: 14px;\n    cursor: pointer;\n}\n</style><body><div id=\"sk-container-id-6\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>RandomForestRegressor(max_depth=30, max_features=15)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-6\" type=\"checkbox\" checked><label for=\"sk-estimator-id-6\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>RandomForestRegressor</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.7/modules/generated/sklearn.ensemble.RandomForestRegressor.html\">?<span>Documentation for RandomForestRegressor</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\" data-param-prefix=\"\">\n        <div class=\"estimator-table\">\n            <details>\n                <summary>Parameters</summary>\n                <table class=\"parameters-table\">\n                  <tbody>\n                    \n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('n_estimators',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">n_estimators&nbsp;</td>\n            <td class=\"value\">100</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('criterion',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">criterion&nbsp;</td>\n            <td class=\"value\">&#x27;squared_error&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_depth',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_depth&nbsp;</td>\n            <td class=\"value\">30</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('min_samples_split',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">min_samples_split&nbsp;</td>\n            <td class=\"value\">2</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('min_samples_leaf',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">min_samples_leaf&nbsp;</td>\n            <td class=\"value\">1</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('min_weight_fraction_leaf',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">min_weight_fraction_leaf&nbsp;</td>\n            <td class=\"value\">0.0</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_features',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_features&nbsp;</td>\n            <td class=\"value\">15</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_leaf_nodes',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_leaf_nodes&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('min_impurity_decrease',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">min_impurity_decrease&nbsp;</td>\n            <td class=\"value\">0.0</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('bootstrap',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">bootstrap&nbsp;</td>\n            <td class=\"value\">True</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('oob_score',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">oob_score&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('n_jobs',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">n_jobs&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('random_state',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">random_state&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('verbose',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">verbose&nbsp;</td>\n            <td class=\"value\">0</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('warm_start',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">warm_start&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('ccp_alpha',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">ccp_alpha&nbsp;</td>\n            <td class=\"value\">0.0</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_samples',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_samples&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('monotonic_cst',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">monotonic_cst&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n                  </tbody>\n                </table>\n            </details>\n        </div>\n    </div></div></div></div></div><script>function copyToClipboard(text, element) {\n    // Get the parameter prefix from the closest toggleable content\n    const toggleableContent = element.closest('.sk-toggleable__content');\n    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;\n\n    const originalStyle = element.style;\n    const computedStyle = window.getComputedStyle(element);\n    const originalWidth = computedStyle.width;\n    const originalHTML = element.innerHTML.replace('Copied!', '');\n\n    navigator.clipboard.writeText(fullParamName)\n        .then(() => {\n            element.style.width = originalWidth;\n            element.style.color = 'green';\n            element.innerHTML = \"Copied!\";\n\n            setTimeout(() => {\n                element.innerHTML = originalHTML;\n                element.style = originalStyle;\n            }, 2000);\n        })\n        .catch(err => {\n            console.error('Failed to copy:', err);\n            element.style.color = 'red';\n            element.innerHTML = \"Failed!\";\n            setTimeout(() => {\n                element.innerHTML = originalHTML;\n                element.style = originalStyle;\n            }, 2000);\n        });\n    return false;\n}\n\ndocument.querySelectorAll('.fa-regular.fa-copy').forEach(function(element) {\n    const toggleableContent = element.closest('.sk-toggleable__content');\n    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n    const paramName = element.parentElement.nextElementSibling.textContent.trim();\n    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;\n\n    element.setAttribute('title', fullParamName);\n});\n</script></body>\n```\n:::\n:::\n\n\n::: {.cell execution_count=60}\n``` {.python .cell-code}\ny_pred = rf_model.predict(x_test)\nmse = mean_squared_error(y_test, y_pred)\nr2 = r2_score(y_test, y_pred)\nprint(f'Mean Squared Error: {mse:.2f}')\nprint(f'R2 Score: {r2:.2f}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean Squared Error: 0.04\nR2 Score: 0.89\n```\n:::\n:::\n\n\nEven after tuning the hyperparameters, the `R2 Score` is `0.88` and `Mean Squared Error` is `0.04` which is same as the previous model, but by using this model we can save memory and time.\n\n",
    "supporting": [
      "laptop_price_prediction_files\\figure-docx"
    ],
    "filters": []
  }
}